### ISSUE TITLE
MySQL connecttion failed

### ISSUE THREAD

**Issue by davidsekielyk** [sprintcube/docker-compose-lamp#10]
Hi, I am a beginner in docker and I am having the following problem.
I can not connect to mysql using mysql_connect in the php file of index.php or test_db.php
try with the data in the file docker-compose.yml try to change the parameters but there is no case.

**Comment by narendravaghela** [comment]
Which version are you using? I mean there are 3 branches for the different version of PHP.
As a quick note, you need to use `mysql` as host to connect with mysql.

**Comment by davidsekielyk** [comment]
Im using version 3

> version: "3"

>services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'png-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: png
      MYSQL_USER: png
      MYSQL_PASSWORD: tiger
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'png-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'png-redis'
    image: redis:latest
    ports:
      - "6379:6379"

and the mysql_connect is this

> $link = mysqli_connect("mysql", "root", "tiger", null);

**Comment by narendravaghela** [comment]
Please use appropriate branch first.
And what errors are you getting for the above connection?

**Comment by davidsekielyk** [comment]
Sorry. I had not seen that you had to choose a branch. I have no problems now

**Comment by narendravaghela** [comment]
Great!!
