### ISSUE TITLE
[BUG] REDIS was hacked on my server... please write some words about it

### ISSUE THREAD

**Issue by denisjoshua** [sprintcube/docker-compose-lamp#100]
First of all, thanks a lot for your docker... it's great work. 
But... I don't know Redis and what it is before to install you docker script. 
I found a miner script on my server and I uderstand that was injected using the 
open port 6379 on Redis. 
I still don't understand how this was possible cause I have csf firewall on the host. 

Anyway I think that you sould tell about this problem on the home page 
cause many people like me (newbe) will have the same problem. 

Here is the bug explained:
http://antirez.com/news/96

Thanks a lot again 
Denis

**Comment by MrOffline77** [comment]
Hi, sorry to hear that youe redis got hijacked. Nevertheless, you are responsible for the things you put in production. This Stack is not build for production usage in purpose .We will mark this more clearly in the readmes.

**Comment by denisjoshua** [comment]
Greate :-)
Thanks a lot again
