### ISSUE TITLE
website:8080 - This site can’t provide a secure connection - phpmyadmin ssl

### ISSUE THREAD

**Issue by manish-fn** [sprintcube/docker-compose-lamp#102]
I recreated your docker-compose file to add letsencypt certs. The site by itself is working fine with the sl but the phpmyamin at 8080 throws an error:

This site can’t provide a secure connection
website sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

I also tried running the site at 8443 but the same error.

Here's my docker-compose file:
version: '3' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      - nextcloud_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    networks:
      - nextcloud_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.2.x-webserver'
    restart: unless-stopped
    networks:
      - nextcloud_network
    depends_on:
      - letsencrypt
      - proxy
      - mysql
    links: 
      - mysql
    environment:
      FR_DB_HOST: mysql
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: superuser
      FR_DB_PASS: superuser
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
      VIRTUAL_HOST: manish.fn
      LETSENCRYPT_HOST: manish.fn
      LETSENCRYPT_EMAIL: manish@fn.co
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2

  mysql:
    build: ./bin/mysql
    container_name: '5.7-mysql'
    restart: unless-stopped
    networks:
      - nextcloud_network
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'sc-phpmyadmin'
    networks:
      - nextcloud_network
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Admin1234
      MYSQL_ROOT_PASSWORD: Admin1234
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin1234
      UPLOAD_LIMIT: 600mb
    ports:
      - '8080:80'
    volumes: 
      - /sessions

  redis:
    container_name: 'sc-redis'
    networks:
      - nextcloud_network
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"

networks:
  nextcloud_network:

**Comment by MrOffline77** [comment]
Hi, you've extented this stack quit heavy :D , so I'm not able to support all kinds of your changes. Please referrer to the phpmyadmin or letsencrypt documentation. Sorry.
