### ISSUE TITLE
Getting Cross Origin headers to work

### ISSUE THREAD

**Issue by josephtan** [sprintcube/docker-compose-lamp#105]
For the PHP 7.2 version (or any) is there a docker-compose file which is able to set a2enmod headers for Cross Origin Policy (CORS)?

If there is how do I do it through a Dockerfile or docker-compose.yml?

Currently I am looking to enable Cross Origin Policy for this docker-compose build.

**Comment by MrOffline77** [comment]
Hi @josephtan !
This should work. You can modify this file: `docker-compose-lamp/bin/webserver/Dockerfile`
At the end of the file you can see 
```
# Enable apache modules
RUN a2enmod rewrite headers
```
You can easily extend this by the apache module you need to activate.
Please let us know if this fixed you issue ;).

**Comment by josephtan** [comment]
Hi @MrOffline77 ,

Yes! It finally worked after I set the v-host default.conf Header set Access-Control-Allow-Origin.
