### ISSUE TITLE
Problem with 5.6 on Mac (please help me its urgent)

### ISSUE THREAD

**Issue by kirumadke** [sprintcube/docker-compose-lamp#107]
Installing header files:           /usr/local/include/php/

warning: mbstring (mbstring.so) is already loaded!

find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f 
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable SOAP support... yes, shared
checking libxml2 install dir... no
checking for xml2-config path... 
configure: error: xml2-config not found. Please check your libxml2 installation.
ERROR: Service 'webserver' failed to build: The command '/bin/sh -c docker-php-ext-install curl     && docker-php-ext-install tokenizer     && docker-php-ext-install json     && docker-php-ext-install mcrypt     && docker-php-ext-install pdo_mysql     && docker-php-ext-install pdo_sqlite     && docker-php-ext-install mysqli     && docker-php-ext-install zip     && docker-php-ext-install -j$(nproc) intl     && docker-php-ext-install mbstring     && docker-php-ext-install soap     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd     && pecl install xdebug-2.5.5 && docker-php-ext-enable xdebug     && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/php.ini' returned a non-zero code: 1

Please help me its urgent

**Comment by MrOffline77** [comment]
First of all, please use our issue templating system to give us more context about your problem, so we and the community can help out better.
Disrespecting this, and screaming for urgency, isn't the kind of culture we want to cultivate in this project. If your problem still exists, please recreate a new propper created issue with some context around your problem.
