### ISSUE TITLE
Can't run it on Fedora 28

### ISSUE THREAD

**Issue by dragonwebeu** [sprintcube/docker-compose-lamp#11]
For some weird reason, I can't run it on Fedora. 
I can only access port 8080 and 6379, other ports are not available.  After docker-compose up http://localhost gives me  "Unable to connect"

Any idea how to fix this?

**Comment by narendravaghela** [comment]
- Please make sure the port 80 is not being used by other applications.
- Try to run `docker-compose up` without `-d` and check if there is any error/warning on output.

**Comment by dragonwebeu** [comment]
>     * Please make sure the port 80 is not being used by other applications.
> 
>     * Try to run `docker-compose up` without `-d` and check if there is any error/warning on output.

The fault was not in port but with user rights/cmod and on Fedora there was something with mysql CONTAINER, which is super weird. I had too many problems with Fedora and changed to Ubuntu now everything works just fine!

**Comment by narendravaghela** [comment]
Glad to hear that!
