### ISSUE TITLE
ERROR: Invalid interpolation format for "phpmyadmin" option in service "services": "${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini"

### ISSUE THREAD

**Issue by RohitChangediya** [sprintcube/docker-compose-lamp#113]
trying to setup docker-compose, getting this error

ERROR: Invalid interpolation format for "phpmyadmin" option in service "services": "${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini"

Please suggest
Rohit

**Comment by MrOffline77** [comment]
Looks like an outdatet docker-compose version. 
What `docker-compose --version` says ? Install the latest version:
https://docs.docker.com/compose/install/
Let us know if this fixed your error.

**Comment by RohitChangediya** [comment]
did update docker-compose to 1.23, still the same error

ERROR: Invalid interpolation format for "webserver" option in service "services": "${DOCUMENT_ROOT-./www}:/var/www/html"

**Comment by RohitChangediya** [comment]
docker-compose version 1.23.2
