### ISSUE TITLE
configure: error: OpenSSL libraries not found.

### ISSUE THREAD

**Issue by Silassiai** [sprintcube/docker-compose-lamp#116]
I am trying to install imap but keep getting this configure: error: OpenSSL libraries not found.

I am using the php74 version

**To Reproduce**
1 - Add following to the Dockerfile
`RUN apt update && apt install -y libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/*`
`RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap`

This is the full error i get:
configure: error: OpenSSL libraries not found.
Check the path given to --with-openssl-dir and output in config.log)
Service 'webserver' failed to build: The command '/bin/sh -c docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap' returned a non-zero code: 1

**Desktop:**
 - OS: Windows 10
 - Docker Version: 2.2.0.5
```
docker -v
Docker version 19.03.8, build afacb8b
```

**Comment by MrOffline77** [comment]
Since this change is not provided by this repository, and we are not able to support changes of people I will close this issue. Sorry.
