### ISSUE TITLE
[BUG] CANNOT change databasename in php 73

### ISSUE THREAD

**Issue by poropo97** [sprintcube/docker-compose-lamp#119]
**Describe the bug**
before execute the docker-compose up command i select the php version 73 and put a database name (diferent than docker) in my .env but when i go to my phpmyadmin i see only one database called docker. Its imposiblr to change name, i've hardcoded the docker-composer.yml MYSQL_DATABASE but still appearing the docker name. I have stopped my docker, clean cache but still having same name docker :(

**Comment by MrOffline77** [comment]
Hi @poropo97 sorry for the delayed response, I was quite busy. 

If you previously started the Database with a different Name, its necessary to delete all content in `data/mysql/` except the `.gitkeep`. Then a new database gets created when the mysql container starts. With the described way it should be enought to just enter you name in your `.env`file. 

Please let me know if this works for you.

**Comment by poropo97** [comment]
It doesn't works, but today I have restarted all my Mac (memory problems) and now the database name is changing, maybe it was my problem. Thanks!
