### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Silassiai** [sprintcube/docker-compose-lamp#120]
Wonderfull LAMP stack. I am using this for my laravel project and everything works exept starting laravel-echo-server. 

what is do is the following:
`docker-compose exec webserver bash`
`cd laravel-project`
`laravel-echo-server start ` (created config file before ofcourse)
I keep getting this redis error.

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

**PHP Version that i use**
php74

When i test `redis-cli` from the webserver i get this:
bash: redis-cli: command not found

when i go into the redis server the `redis-cli` works.
but the `redis-server` command gives this error in there:
root@fcc7b56abafa:/data# redis-server
39:C 19 May 2020 14:35:02.746 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
39:C 19 May 2020 14:35:02.746 # Redis version=6.0.2, bits=64, commit=00000000, modified=0, pid=39, just started
39:C 19 May 2020 14:35:02.746 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/
redis.conf
39:M 19 May 2020 14:35:02.747 # Could not create server TCP listening socket *:6379: bind: Address already in use
root@fcc7b56abafa:/data#

Hope someone can help

**Comment by MrOffline77** [comment]
Hi @Silassiai ,

thanks for using this stack !

`[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)`
Looks like you set your redis TCP destination to an ip. From inside the docker container the service ca reach redis via `redis:6379`that should work probably some `.env`stuff in you echo server. 

You dont need to execute the `redis-server`command, this is docker already doing for you. Most php stuff is using predis via composer or something similar to connect. But i guess that problem solves it self when you adjust your `.env`file cause you dont need the redis-cli then anymore. 
You can install it via classic debian commands 
`apt-get update &&
apt-get install redis-cli` not sure how debian named this but something like this should work too. 

Please let me know if this works for you.

**Comment by MrOffline77** [comment]
This issue looks abdoned, so I'm going to close this.
