### ISSUE TITLE
[BUG] PHP 5.4 Error

### ISSUE THREAD

**Issue by yohanes-ai** [sprintcube/docker-compose-lamp#121]
**Describe the bug**
failed on docker-compose up -d. always stuck on Reading package lists...
I try on 5.6 and it works

**which Branch / PHP Version are you using ?**
php54

**To Reproduce**
1. git clone https://github.com/sprintcube/docker-compose-lamp.git
2. change .env file
3.  PHPVERSION=php54

docker-compose up -d
Building webserver
Step 1/13 : FROM php:5.4-apache
 ---> f04f77c9186f
Step 2/13 : RUN cp /etc/apt/sources.list /etc/apt/sources.list.old &&     cat /dev/null > /etc/apt/sources.list
 ---> Using cache
 ---> 9682aa588757
Step 3/13 : RUN printf "deb http://archive.debian.org/debian/ jessie main\n" > /etc/apt/sources.list &&     printf "deb-src http://archive.debian.org/debian/ jessie main\n" >>  /etc/apt/sources.list &&     printf "deb http://security.debian.org jessie/updates main\n" >>  /etc/apt/sources.list &&     printf "deb-src http://security.debian.org jessie/updates main" >>  /etc/apt/sources.list
 ---> Using cache
 ---> 889c337ba5bb
Step 4/13 : RUN apt-get -y update && apt-get upgrade -y
 ---> Running in e50b2e84af0d
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://archive.debian.org jessie InRelease
Get:2 http://archive.debian.org jessie Release.gpg [2420 B]
Get:3 http://archive.debian.org jessie Release [148 kB]
Ign http://archive.debian.org jessie Release
Get:4 http://archive.debian.org jessie/main Sources [9169 kB]
Get:5 http://security.debian.org jessie/updates/main Sources [452 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [978 kB]
Get:7 http://archive.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 19.9 MB in 20s (952 kB/s)
Reading package lists...
W: There is no public key available for the following key IDs:
AA8E81B4331F7F50
W: GPG error: http://archive.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1587841717
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  xz-utils
Use 'apt-get autoremove' to remove it.
The following packages will be upgraded:
  apache2 apache2-bin apache2-data apache2-utils apache2.2-common apt
  base-files bash binutils ca-certificates cpp-4.9 curl debconf debconf-i18n
  debian-archive-keyring dmsetup dpkg e2fslibs e2fsprogs file g++-4.9 gcc-4.9
  gcc-4.9-base gnupg gpgv inetutils-ping libapt-pkg4.12 libasan1 libatomic1
  libbz2-1.0 libc-bin libc-dev-bin libc6 libc6-dev libcilkrts5 libcomerr2
  libcurl3 libdb5.3 libdevmapper1.02.1 libexpat1 libffi6 libgcc-4.9-dev
  libgcc1 libgcrypt20 libglib2.0-0 libgnutls-deb0-28 libgomp1 libgssapi-krb5-2
  libhogweed2 libidn11 libitm1 libk5crypto3 libkrb5-3 libkrb5support0
  libldap-2.4-2 liblsan0 libmagic1 libncurses5 libncursesw5 libnettle4
  libpam-modules libpam-modules-bin libpam-runtime libpam0g libpcre3
  libprocps3 libquadmath0 librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0
  libss2 libssh2-1 libssl1.0.0 libstdc++-4.9-dev libstdc++6 libsystemd0
  libtasn1-6 libtinfo5 libtsan0 libubsan0 libudev1 libxml2 linux-libc-dev
  login multiarch-support ncurses-base ncurses-bin openssl passwd perl
  perl-base perl-modules procps sed sensible-utils systemd systemd-sysv tar
  tzdata udev zlib1g
102 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 82.2 MB of archives.
After this operation, 3905 kB disk space will be freed.
WARNING: The following packages cannot be authenticated!
  base-files dpkg binutils ncurses-bin libdb5.3 sed debian-archive-keyring
  ncurses-base libtinfo5 libncursesw5 libncurses5 debconf-i18n debconf
  libpam0g libpam-modules-bin libpam-modules libpcre3 dmsetup
  libdevmapper1.02.1 libhogweed2 libnettle4 libpam-runtime
E: There are problems and -y was used without --force-yes
ERROR: Service 'webserver' failed to build: The command '/bin/sh -c apt-get -y update && apt-get upgrade -y' returned a non-zero code: 100

.env file
# Please Note: 
# - In PHP Versions <= 7.4 MySQL8 is not supported due to lacking pdo support

# Possible values: php54, php56, php71, php72, php73, php74
PHPVERSION=php54
DOCUMENT_ROOT=./www
VHOSTS_DIR=./config/vhosts
APACHE_LOG_DIR=./logs/apache2
PHP_INI=./config/php/php.ini

# Possible values: mariadb, mysql, mysql8
DATABASE=mysql
MYSQL_DATA_DIR=./data/mysql
MYSQL_LOG_DIR=./logs/mysql

# If you already have the port 80 in use, you can change it (for example if you have Apache)
HOST_MACHINE_UNSECURE_HOST_PORT=80
HOST_MACHINE_SECURE_HOST_PORT=443

# If you already have the port 3306 in use, you can change it (for example if you have MySQL)
HOST_MACHINE_MYSQL_PORT=3306

# If you already have the port 6379 in use, you can change it (for example if you have Redis)
HOST_MACHINE_REDIS_PORT=6379

# MySQL root user password
MYSQL_ROOT_PASSWORD=tiger

# Database settings: Username, password and database name
MYSQL_USER=docker
MYSQL_PASSWORD=docker
MYSQL_DATABASE=docker

**Expected behavior**
1 week before, it works. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Docker Version:
```
docker -v
Docker version 19.03.8, build afacb8b
```

**Comment by MrOffline77** [comment]
Looks like you cant reach the debian servers. Are you behind some sort of http proxy ? 
I'will check if I'am able to reproduce this.

**Comment by Kasui92** [comment]
Hi @MrOffline77 ,
I'm having the same error reported in this issue. I don't have any kind of proxy, I run docker on Windows 10 on WSL2, but even trying with the prompt/powershell doesn't seem to work. 

![immagine](https://user-images.githubusercontent.com/15154851/83519465-555add00-a4dc-11ea-89b9-819d644ea80d.png)

Ty!

**Comment by MrOffline77** [comment]
I will check.

**Comment by MrOffline77** [comment]
Please rebuild your images and let me know if this works for your. Not the best solution but, as of know it works on my side.

**Comment by Kasui92** [comment]
Hello @MrOffline77 !
It works perfectly. Thank you very much!
