### ISSUE TITLE
[BUG] Can't connect to database

### ISSUE THREAD

**Issue by Kasui92** [sprintcube/docker-compose-lamp#123]
**Describe the bug**
I'm trying to connect to the database, but I always get the following error:

![immagine](https://user-images.githubusercontent.com/15154851/83279384-51297980-a1d5-11ea-98b8-eb748b256c86.png)

When I run the docker ps command known as webserver_database it is always restarting, with exit code 1:

![immagine](https://user-images.githubusercontent.com/15154851/83279789-f04e7100-a1d5-11ea-9fb5-3f8f907a5a8e.png)

**which Branch / PHP Version are you using ?**
php56

**To Reproduce**

    git clone https://github.com/sprintcube/docker-compose-lamp.git
    change .env file
    PHPVERSION=php56
    See error

**Expected behavior**
I expect to connect to the DB

**Screenshots**
(see descrition)

**Desktop (please complete the following information):**
 - OS: Windows [WSL2 Ubuntu20.04]
 - Browser Chrome
 - Docker Version:
```
docker -v
Docker version 19.03.8, build afacb8b7f0
```

**Comment by MrOffline77** [comment]
Hi @Kasui92 If i remember correctly, this sounds familiar to me. There was something with ubuntu and WSL. I try to search for it in the closed issues.

**Comment by MrOffline77** [comment]
Can you post us the error logs of the mysql container please ? 

Also please take a look at this issues, please note that the mentioned docker-compose file looks a little bit different back then, but in general you could give it a shot. 

#67 
#41

**Comment by Egahras** [comment]
I got the same problems some days ago.  I'm using WSL2 Ubuntu 20.04, too.
I got the problems with mysql, and later some problems with wordpress while "uploading" plugins. 
I figured out that its a problem with the /mnt permissions.

I followed [this description](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/) and remounted the volume with DrvFs to solve my problem. 
#41  seems to follow the same approach.

**Comment by Kasui92** [comment]
Hi everyone,
I really thank you in advance for your answers!

I had already seen those issues and adopted the solutions, but without success. The error I kept getting was the following.

![Annotazione 2020-05-29 230712](https://user-images.githubusercontent.com/15154851/83307559-4ab2f600-a205-11ea-9979-94f2be93a163.png)

However, following the advice of @Egahras and remounting the volume, it seems to have worked properly and now I no longer receive that error.

Thanks again to everyone for the excellent support!
