### ISSUE TITLE
[BUG] Cannot connect to database in linux machine

### ISSUE THREAD

**Issue by ahmad-shiddiq** [sprintcube/docker-compose-lamp#125]
**Describe the bug**
Fresh install cannot connect to database

**which Branch / PHP Version are you using ?**
php74

**To Reproduce**
1. clone from git
2. run `docker-compose up -d`
3. open in browser
4. see error

**Expected behavior**
connected to database without problem

**Screenshots**
![Screenshot_20200614_134831](https://user-images.githubusercontent.com/53107961/84587031-e9666600-ae45-11ea-9c51-b896d6a10445.png)
![Screenshot_20200614_134914](https://user-images.githubusercontent.com/53107961/84587032-ec615680-ae45-11ea-9525-a15441e22ad2.png)
![Screenshot_20200614_134849](https://user-images.githubusercontent.com/53107961/84587034-eec3b080-ae45-11ea-9ae7-e1d41ee94f9f.png)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser Brave
 - Docker Version: 
```
docker -v
Docker version 19.03.11-ce, build 42e35e61f3
```
**Additional context**
I already read a lot from closed bug in this repo, but it didnt work.

**Comment by MrOffline77** [comment]
Is there stuff like app armor or selinux present in manjaro ?

**Comment by MrOffline77** [comment]
Please try to directly login with the `root``tiger` logins and not the `docker``docker` creds. Let me know if this works.

**Comment by AhmadShiddiq** [comment]
> Is there stuff like app armor or selinux present in manjaro ?

I just checked it, but there aren't both

**Comment by ahmad-shiddiq** [comment]
UPDATE: last try i just prune all my docker system and start from zero, and now its work :)
