### ISSUE TITLE
[BUG] Links in the sample page in a customized port (8081) don't work

### ISSUE THREAD

**Issue by zetxek** [sprintcube/docker-compose-lamp#126]
**Describe the bug**
Using a customized port, such as `8081`, will make the default links in the `index.php` file not work because they're hardcoded:

So visiting:
http://localhost:8081/

And clicking in `phpinfo()`, or Test DB connection will fail

**which Branch / PHP Version are you using ?**
php74

**To Reproduce**
1. Customize `.env` to use 8081 as insecure port
2. Load the project in the browser, with http://localhost:8081/
3. Click in `phpinfo()`

**Expected behavior**
The links should work also for non-default ports.

**Screenshots**

![image](https://user-images.githubusercontent.com/240085/84761390-a3d2a600-afc9-11ea-9f8a-fd030dc96c03.png)

**Comment by MrOffline77** [comment]
Hi @zetxek does the 16211bb solved this problem too, so we could close this issue, correct ?

**Comment by zetxek** [comment]
Yes, 16211bb fixes this issue. We can close!
