### ISSUE TITLE
Add exif and imagick modules

### ISSUE THREAD

**Issue by STV11C** [sprintcube/docker-compose-lamp#128]
**About which PHP Version we are talking ?**
7.3

**Is your feature request related to a problem? Please describe.**
WordPress suggests **exif** and **imagick** as installed modules.

**Describe the solution you'd like**
Please add PHP modules as WordPress is a popular CMS. 

**Describe alternatives you've considered**
I tried to add them to the php73 Dockerfile (following the other modules), but couldn't get it to work. I completed a docker-compose build too but got an error that imagick didn't exist. Thanks

**Additional context**

**Comment by MrOffline77** [comment]
I will take a look at this.

**Comment by MrOffline77** [comment]
@STV11C if added the modules. Please get a fresh clone of master and make sure that your webserver image is rebuilding without caching.  Wordpress should work then. Please verify and let me know. 

<img width="963" alt="Bildschirmfoto 2020-06-30 um 20 39 04" src="https://user-images.githubusercontent.com/43014876/86164385-fa83c800-bb11-11ea-9460-e72336412632.png">
<img width="949" alt="Bildschirmfoto 2020-06-30 um 20 38 54" src="https://user-images.githubusercontent.com/43014876/86164390-fc4d8b80-bb11-11ea-860b-f36d0b09d1e3.png">
