### ISSUE TITLE
[BUG] Error reading the CPU table

### ISSUE THREAD

**Issue by trelljaret** [sprintcube/docker-compose-lamp#133]
**Describe the bug**
On 'Building webserver' step, it fails on the command 'RUN apt-get'

**which Branch / PHP Version are you using ?**
php74

**To Reproduce**
1. Setup an Ubuntu Mate 18.04.3 VM
2. Install docker snap
3. install docker compose
4. Do the rest as described in the manual of this repository

**Expected behavior**
It will fail with permission error problems. This is the whole log that it outputs:

```
john@john-vm:~/Documents/projects/sprintcube-docker-compose-lamp/docker-compose-lamp$ docker-compose up -d
Building webserver
Step 1/12 : FROM php:7.4.2-apache-buster
 ---> 4165e46dd82e
Step 2/12 : USER 0
 ---> Using cache
 ---> 2b718d0e657f
Step 3/12 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 090331e4cb0d
Step 4/12 : RUN apt-get -y update --fix-missing &&     apt-get upgrade -y &&     apt-get --no-install-recommends install -y apt-utils &&     rm -rf /var/lib/apt/lists/*
 ---> Running in e6e5eeb11a06
W: Unable to read /etc/apt/apt.conf.d/01autoremove - open (13: Permission denied)
W: Unable to read /etc/apt/apt.conf.d/70debconf - open (13: Permission denied)
W: Unable to read /etc/apt/apt.conf.d/docker-autoremove-suggests - open (13: Permission denied)
W: Unable to read /etc/apt/apt.conf.d/docker-clean - open (13: Permission denied)
W: Unable to read /etc/apt/apt.conf.d/docker-gzip-indexes - open (13: Permission denied)
W: Unable to read /etc/apt/apt.conf.d/docker-no-languages - open (13: Permission denied)
E: Error reading the CPU table
ERROR: Service 'webserver' failed to build: The command '/bin/sh -c apt-get -y update --fix-missing &&     apt-get upgrade -y &&     apt-get --no-install-recommends install -y apt-utils &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
john@john-vm:~/Documents/projects/sprintcube-docker-compose-lamp/docker-compose-lamp$ 
```

And btw, I haven't changed the `.env` file.

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 18.04.3
 - Browser chrome
 - Docker Version:
```
docker -v
Docker version 18.09.9, build 1752eb3
```
**Additional context**
Is it because of docker snap? Im just curious. Will test myself with a clean manual install, but wanted to know if anybody has this problem with docker snap.

**Comment by MrOffline77** [comment]
Hi @trelljaret 
I've just verified that the php72 image is building. No Problems here with MacOS and Docker. I'm not an Ubuntu expert. Maybe some apparmor thing or a privilege thing. You can try to run the Containers in privileged mode. Looks like your Container is not allowed to access your network stack for some security reasons.

**Comment by trelljaret** [comment]
Looks like it was from docker snap.  
The source of problem has been identified.  => `Docker Snap`
Using default manual install had no problems.
I will close this issue.
