### ISSUE TITLE
How to add composer to LAMP Stack

### ISSUE THREAD

**Issue by freebornforever** [sprintcube/docker-compose-lamp#137]
Please let me know how to add composer to docker-compose-lamp.

Thanks in advance

**Comment by stloc** [comment]
have you the solution ?

**Comment by freebornforever** [comment]
> have you the solution ?

It already come with composer.

**Comment by stloc** [comment]
how to run composer install after docker-compose up ?

**Comment by stloc** [comment]
Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 8

it is normal because we must install vendor on running but where to set composer install ?

**Comment by freebornforever** [comment]
> how to run composer install after docker-compose up ?

I used terminal in docker container to test it.

**Comment by freebornforever** [comment]
> Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 8
> 
> it is normal because we must install vendor on running but where to set composer install ?

composer was installed in /usr/local/bin try connect your container using terminal and test it
