### ISSUE TITLE
[BUG] GD library not enabled

### ISSUE THREAD

**Issue by alessandroalessio** [sprintcube/docker-compose-lamp#138]
In my latest installation of docker-compose-lamp with PHP 7.4 the GD libraries are not enable (and maybe installed). I've try to get phpinfo() and the items of GD  doesn't exist. 

Anyone has this problem?

**Comment by MrOffline77** [comment]
Hi @alessandroalessio ,
I remember #112 - there was a GD issue. Do you use the "new" master branch, or are you using the php74 branch ? The GD change was only applied to the master branch. Maybe this is the problem. 
If not, please let me know, then I will take a deeper look at this.

**Comment by MrOffline77** [comment]
I just created a fresh build of the php74 image against master branch. Php info tells me GD is enabled. Looks ok to me.

**Comment by alexdrago** [comment]
I'm having that same problem too. And I don't have any old compilations.

**Comment by MrOffline77** [comment]
@alessandroalessio @alexdrago 
Can you tell me how I can test and verify that GD ist working ? 
Then I can take a deeper look at this.
