### ISSUE TITLE
[Question] How to properly change the username and password of the MySQL db?

### ISSUE THREAD

**Issue by kartikynwa** [sprintcube/docker-compose-lamp#139]
Hello. I am new to docker/docker-compose so pardon my ignorance.

I changed the username and password variables in the `.env` file. Then I ran `docker-compose build`. But after doing this, PHPMyAdmin cannot access the database anymore.

Thanks for making this repo public. It's very helpful. :)

**Comment by MrOffline77** [comment]
Hi,
I guess you started the stack previously. You need to remove everything from `data/mysql/*`. Afterwards mysql will start a new instance and will initialize with you new credentials.

**Comment by kartikynwa** [comment]
It did work but I think the problem lies with the particular password I have chosen for the `$MYSQL_PASSWORD` environment variable since it contains symbols which are causing problems. Changing the password to something simpler like `testpass` works perfectly. I will test a bit more and let you know. Thanks a lot for the help.

**Comment by kartikynwa** [comment]
Updated to docker-compose 1.26.2 (latest) which uses python-dotenv to parse the .env file. The issue still persists but I will close the issue because it looks like it is related to a limitation of docker-compose itself. Thanks for your help.
