### ISSUE TITLE
How to install tidy?

### ISSUE THREAD

**Issue by Dudo1985** [sprintcube/docker-compose-lamp#140]
I've added this line 

`RUN apt-get install -y php-tidy`

and then 

`docker-php-ext-install tidy`

on my php74/Dockerfile but with no luck, I've 

`Unable to locate package php-tidy`

How can I install and enable tidy?

Thank you!

**Comment by MrOffline77** [comment]
Hello @Dudo1985 
sorry for the delay. You can add this part after the docker-php-ext-install part in the dockerfile. 
```
# Libtidy
RUN apt-get update && apt-get -y --no-install-recommends install --fix-missing libtidy-dev && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-install tidy && \ 
    docker-php-ext-enable tidy
```

<img width="987" alt="Bildschirmfoto 2020-10-03 um 12 47 06" src="https://user-images.githubusercontent.com/43014876/94989661-c4be0780-0576-11eb-8c1b-0f750a4b7567.png">


Please let me know if this solved your problem.

**Comment by Dudo1985** [comment]
I've been finally able to test it, and it worked.

Will you consider to insert it?

Thank you!

**Comment by MrOffline77** [comment]
Feel free to create a pull request an explain why we or most php devs need this :).
