### ISSUE TITLE
[FEATURE] PEAR 

### ISSUE THREAD

**Issue by Kasui92** [sprintcube/docker-compose-lamp#141]
Hello,
For a project I am building I would need to be able to point to the pear.php file. 
Browsing in the webserver container I was unable to locate it.

Am I wrong to look for it or is it just not implemented?

If so, could I have any indication of this? 
I think it might be useful to have it for php version 5.4 and 5.6.

Thanks for the amazing work.

**Comment by MrOffline77** [comment]
Hello @Kasui92 
thanks for the compliments. The `pear.php` is available at `/usr/local/lib/php/PEAR.php`. 
Let me know if this solved your problem.

**Comment by Kasui92** [comment]
Found It! 
Problem solved.

Thank you for your help and have a good day!
