### ISSUE TITLE
[Question] How to setup localhost domain name for dockerised site.

### ISSUE THREAD

**Issue by Abhinav1217** [sprintcube/docker-compose-lamp#150]
During localhost development, I have a habit of assigning domain names like 
```
project-name.localhost  --> www/project-name
pma.project-name.localhost --> phpmyadmin
admin.project-name.localhost  --> www/project-name/admin
```

How do I modify my `/etc/hosts` to create such domains for docker container. 

I am currently tasked to update an old legacy project from 5.6 to 7.4. 

I have managed to modify the docker files to have both `php 5.6 at localhost:8056` and `php 7.4 at localhost:8074` running same time (currently sharing same db container I plan to change that) .  But I want to assign domain like `project56.localhost`  and `project7.localhost` on them.

**Comment by dealenx** [comment]
Hello, 

You need to set an environment config for your container:
``` yml
  webserver:
   ...
    environment:
        VIRTUAL_HOST: project7.localhost
....
```

And  of course to do same with your second  container.

Hope it helps.

**Comment by MrOffline77** [comment]
Closed since this looks like it is resolved. Thanks @dealenx

**Comment by Abhinav1217** [comment]
Sorry I totally forgot to reply to this. Yes it worked. I had some trouble with dynamic subdomains which took some hit and trials with configurations in .htaccess for it to work.
