### ISSUE TITLE
OPCode Caching Drupal 8

### ISSUE THREAD

**Issue by Edgecrusher2112** [sprintcube/docker-compose-lamp#159]
I am new to Docker, and having a mess about with this container.

I am trying to install Drupal 8 on it. I know it's end of life is in November but a friend's hosting is a bit behind so want to use Docker to match the hosting specs). I want to use a Docker LAMP setup for other bits and pieces too on the same shared hosting so have stayed away from some Drupal Docker containers, think it suits me better just using a Docker LAMP stack.

I am getting an issue, regardless of whether I use the default .env DB user settings, or create a new user in PHPMyAdmin when installing Drupal.

Alll I am getting is this (the localhost page DB links say the connection is fine).

<img width="772" alt="Screenshot 2021-06-16 at 15 41 15" src="https://user-images.githubusercontent.com/4696617/122240787-f1723f00-ceb9-11eb-84a0-7ac4390ce3c2.png">

I really don't know what's causing this, and forgive me if I'm missing something obvious but any help would be greatly appreciated.

Thanks in advance.

**Comment by MrOffline77** [comment]
Try to point your drupal to a Database Host not running on 127.0.0.1. 
You need to tell him to connect to `database` like the name of the container in the compose file. You can checkout the php mysql connection test file in the `www` directory for an  example.

**Comment by Edgecrusher2112** [comment]
Thanks for this. I will get a chance to have a look tomorrow.
