### ISSUE TITLE
How to Copy and Install Security Certificate file

### ISSUE THREAD

**Issue by sandipt27** [sprintcube/docker-compose-lamp#160]
I have **abc.cer** Certificate file stored at root level viz., C:\docker-compose-lamp which for security reasons needs to be installed.  In one of other setup I used back in past, I used to mention the line "COPY abc.cer /usr/share/ca-certificates/abc.cer" in Dockerfile at root and it was working fine.  Here, there is no Dockerfile at root so I picked up php8 Dockerfile at C:\docker-compose-lamp\bin\php8\Dockerfile and mentioned below lines in there :

> COPY abc.cer /usr/share/ca-certificates/abc.cer
> RUN openssl x509 -inform der -in /usr/share/ca-certificates/abc.cer -out /usr/share/ca-certificates/abc.pem
> RUN mv /usr/share/ca-certificates/abc.pem /usr/share/ca-certificates/abc.crt
> RUN rm /usr/share/ca-certificates/abc.cer

I however had kept .cer file at root level i.e. at **C:\docker-compose-lamp\** folder 

Upon docker-compose command it returns error as **failed to compute cache key: "/abc.cer" not found: not found** 

Of course it's failing to locate the .cer file. so question is : 
What needs to be done ? And where should these lines to be mentioned ? Or Where should I place these Certificate files ?

Thanks

**Comment by MrOffline77** [comment]
You can reference to a local certificate in the vhost config and mount the file as volume into the docker container. 
In the docker-compose file are some places were volumes are used. Just add your line and modify by your needs.
