### ISSUE TITLE
To Enable more modules

### ISSUE THREAD

**Issue by sandipt27** [sprintcube/docker-compose-lamp#161]
The README.md file states that _If you want to enable more modules, just update `./bin/webserver/Dockerfile`_

But I checked and there is no Directory named "webserver" and no file named "Dockerfile" in it.  I understand, I might need to create one.  But I don't know what format should that file be ?  If you could give one sample file to use for WebServer, would be great.  That would minimize the error occurrence during the setup and save some time of ours.

Thanks a lot for a nice work you've done.

**Comment by MrOffline77** [comment]
You can edit the `./bin/phpX/Dockerfile` File to add you modules. 
I'm going to fix this reference in the readme.
