### ISSUE TITLE
[BUG] Fails to install 'xdebug', 'json', 'opcache', 'redis' and 'imagick'.

### ISSUE THREAD

**Issue by sandipt27** [sprintcube/docker-compose-lamp#162]
**Describe the bug**
In my Dockerfile in C:\docker-compose-lamp\bin\php8 I have  
1. **Mentioned line** : docker-php-ext-enable xdebug
**Gives error** : No releases available for package "pecl.php.net/xdebug"
executor failed running [/bin/sh -c pecl install xdebug-3.0.0 &&     docker-php-ext-enable xdebug]: exit code: 1
2. **Mentioned line** : RUN pecl install redis-5.3.3 && docker-php-ext-enable redis
**Gives error** : No releases available for package "pecl.php.net/redis"
3. For **imagick** installation
**Gives error** : Cloning into 'imagick'...
fatal: unable to access 'https://github.com/Imagick/imagick/': server certificate verification failed. CAfile: none CRLfile: none
4. **One more error** received during setup : 
**Error** : Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20200930/
cp: cannot stat 'modules/*': No such file or directory 

I had to comment all related commands off of Dockerfile to continue setup.

**which Branch / PHP Version are you using ?**
php8

**To Reproduce**
Error:
 Fails after hitting the command : "docker-compose up -d"

**Expected behavior**
Ideally it should install those extensions.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Ubuntu] : Windows
 - Browser [e.g. chrome, safari] : chrome
 - Docker Version:
```
docker -v
Docker version 20.10.6
```
**Additional context**

**Comment by MrOffline77** [comment]
This sounds like a local problem. I can't reproduce this.
