### ISSUE TITLE
Max upload for PHPMyAdmin

### ISSUE THREAD

**Issue by WillyBaldy** [sprintcube/docker-compose-lamp#163]
It seems that to be able to set the max file upload limit for PHPMyAdmin (for imports) the default php.ini file in ./config/php won't work. I'm not sure if it ever worked, but there's a /usr/local/etc/php/conf.d/phpmyadmin-misc.ini file that interferes with this. The proper way to set the upload limit of the PHPMyAdmin docker container is by using environment variables. In my .env I added:

```
# PHPMyAdmin
UPLOAD_LIMIT=512M
MEMORY_LIMIT=512M
```

then in my docker-compose.yaml I added the following to phpmyadmin:environment:

```
UPLOAD_LIMIT: ${UPLOAD_LIMIT}
MEMORY_LIMIT: ${MEMORY_LIMIT}
```

Hopefully this will help someone having the same problem I had.

**Comment by wdebusschere** [comment]
@WillyBaldy Thank you for this, solved our problem!

**Comment by MrOffline77** [comment]
#170 fixes this problem.
