### ISSUE TITLE
PHP version isn't applying[BUG]

### ISSUE THREAD

**Issue by VladimirMaljkovic** [sprintcube/docker-compose-lamp#164]
When I set the php version using .env file, that container gets the latest version of php anyway

**which Branch / PHP Version are you using ?**
php74

**To Reproduce**
1. Clone repo
2. `cp sample.env .env`
3. Inside the .env file, set PHPVERSION=php74 and DATABASE=mysql
4. `docker-compose up`

**Expected behavior**
I get php version 7.4

**Actual behaviour**
My php version becomes 8.0.3

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Browser: /
 - Docker Version: 
```
docker -v
Docker version 20.10.7, build f0df350
```
-docker-compose version:
docker-compose version 1.29.1, build c34c88b2

**Additional context**

**Comment by MrOffline77** [comment]
Just add the build flag to rebuild the container or you can remove the existing image.
`docker-compose build `

**Comment by VladimirMaljkovic** [comment]
I'm a dummy, thanks so much
