### ISSUE TITLE
[BUG] Cannot find save handler 'redis'

### ISSUE THREAD

**Issue by akulmambetov** [sprintcube/docker-compose-lamp#166]
**Describe the bug**
No connection to redis

**which Branch / PHP Version are you using ?**
php74

I tried

my php.ini config
```
session.save_handler = redis
session.save_path = "tcp://redis:6379"

or 

session.save_path = "tcp://lamp-redis:6379"

or

session.save_path = "tcp://127.0.0.1:6379"
```

![Screenshot_20210712_105825](https://user-images.githubusercontent.com/54025480/125233506-84a76480-e300-11eb-8772-950c9d1e0945.png)

**Comment by MrOffline77** [comment]
Im not able to reproduce this. Is this still an issue with the latest code base and a clean setup ?
