### ISSUE TITLE
[BUG] - failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest

### ISSUE THREAD

**Issue by jeetendra-choudhary** [sprintcube/docker-compose-lamp#167]
**Describe the bug**
When I am trying to build the image with MySql8 and PHP 8 I am not able to build the image it fails with error - `Service 'Database' failed to build : Build failed.

**which Branch / PHP Version are you using ?**
php8

**To Reproduce**
1. Clone repository
2. Update the environment file as required
3. Run command - #docker-compose build  or #docker-compose up --build
```
docker-compose build
Building database
[+] Building 1.2s (3/3) FINISHED                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 139B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/mysql:8                                                                                       1.1s
------
 > [internal] load metadata for docker.io/library/mysql:8:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:52b8406e4c32b8cf0557f1b74517e14c5393aff5cf0384eff62d9e81f4985d4b: not found
```

**Expected behavior**
The image should be able to build.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.4 with M1 Chip
 - Browser Safari (Not Applicable)
 - Docker Version: Docker Desktop - Version 3.5.2 (3.5.2.18)
 
docker -v
Docker version 20.10.7, build f0df350

**Comment by MrOffline77** [comment]
This is probably due to the Apple M1 chip. The chip is based on ARM and not on the x86 architecture. The Docker containers we build are derived from and built on Dockerhub upstream images. The upstream images don't seem to be built against the M1 so far. I'll take a look at that in the days to come to see if there are ARM images available in the meantime. We would then have to make that selectable in the env.

**Comment by Blackoasissun** [comment]
Is there something on that? I can confirm the error on a Apple M1 chip

**Comment by multispace88** [comment]
@MrOffline77 any news on a possible M1 chip fix?
I can confirm the error stated above using a M1 Pro chip.

**Comment by MrOffline77** [comment]
Looks like php now got some M1 compatible containers. MySQL still does not have M1 "ok" container. 
Please try to use mariadb and let me know what the errors are during startup. Sadly i have no M1 Hardware available at the moment. So i need you to help me a little bit :). Thanks for testing.

**Comment by sergey-kukosh** [comment]
`version: "3"

services:
  webserver:
    build: 
      context: ./bin/${PHPVERSION}
    container_name: '${COMPOSE_PROJECT_NAME}-${PHPVERSION}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  database:
    image: mysql:8.0.19
    platform: 'linux/x86_64'
    build:
      context: "./bin/${DATABASE}"
    container_name: '${COMPOSE_PROJECT_NAME}-${DATABASE}'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  redis:
    container_name: '${COMPOSE_PROJECT_NAME}-redis'
    image: redis:latest
    ports:
      - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
`
solution for M1 
 need add this 
 `    image: mysql:8.0.19
    platform: 'linux/x86_64'`

**Comment by MrOffline77** [comment]
@sergey-kukosh please set your database version to the mariadb versions instead of the mysql images in the env file.

**Comment by sheetalj2205** [comment]
Hello, @MrOffline77 
I am also getting the same error with `docker compose  up` command. Is there someone who can help in solving this error?

Here is the link to question with details: [https://stackoverflow.com/questi
<img width="1361" alt="Screen Shot 2023-02-02 at 2 26 29 PM" src="https://user-images.githubusercontent.com/64475191/216342508-7e39d93f-fbff-439c-b607-56d52286cf5a.png">
ons/75324019/error-on-running-the-command-docker-compose-up-in-macbookapple-m1-pro](url)
