### ISSUE TITLE
[BUG] Not working mysql on ubuntu 20.04

### ISSUE THREAD

**Issue by danyk4** [sprintcube/docker-compose-lamp#172]
**Describe the bug**
I changed in .env phpversion=56 and database=mysql
Phpinfo is working
On localhost errors:
Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/index.php on line 34
Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/index.php on line 34
Warning: mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/index.php on line 44

Can't enter phpmyadmin - permission denied 

Test DB PDO error:
Error: Unable to connect to MySQL. Error: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/test_db_pdo.php:9 Stack trace: #0 /var/www/html/test_db_pdo.php(9): PDO->__construct('mysql:host=data...', 'root', 'tiger') #1 {main}

**which Branch / PHP Version are you using ?**
php56

**To Reproduce**
1.  docker-compose up -d
2. go to localhost

**Expected behavior**
a working lamp

**Screenshots**
uploaded

**Desktop (please complete the following information):**
 - OS: Ubuntu
 -  Browser - chrome, ff
 - Docker Version: 
```
docker -v

Docker version 20.10.8
```
**Additional context**
--
![2021-09-08_10-28](https://user-images.githubusercontent.com/22352208/132467195-e405b056-d32f-4ef9-8a5b-a83d1427d8fa.png)

**Comment by MrOffline77** [comment]
Can you exec in one of the containers and try a `ping mysql`please ? 
Looks like the resolution of the linked containers are not working properly on your system. 
Are you using some special docker network configs ?

**Comment by dkostroma** [comment]
I enter 

docker-compose exec webserver bash

then

root@3baf32a66ded:/var/www/html# ping database
bash: ping: command not found

then i enter

root@3baf32a66ded:/var/www/html# mysql -V
mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

and then

root@3baf32a66ded:/var/www/html# mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")

**Comment by dkostroma** [comment]
and no i have no  special docker network configs it's a fresh install

**Comment by dkostroma** [comment]
root@3baf32a66ded:/var/www/html# service mysql status
mysql: unrecognized service

**Comment by tourtools** [comment]
same behaviour on macos bigsur:
```
root@a8d8e6e395b4:/var/www/html# service mysql status
mysql: unrecognized service
root@a8d8e6e395b4:/var/www/html# mysql -uroot -p
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by tourtools** [comment]
to me it solves using "database" as the host:
```
root@a8d8e6e395b4:/var/www/html# mysql -h database -uroot -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 79
Server version: 10.5.12-MariaDB-1:10.5.12+maria~focal mariadb.org binary distribution
```

**Comment by u2dev** [comment]
> to me it solves using "database" as the host:
> 
> ```
> root@a8d8e6e395b4:/var/www/html# mysql -h database -uroot -p
> Enter password:
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 79
> Server version: 10.5.12-MariaDB-1:10.5.12+maria~focal mariadb.org binary distribution
> ```

change "localhost or 127.0.0.1" to "database" it work.

**Comment by MrOffline77** [comment]
I guess this works because the containers themself does not have a loopback localhost. 
PHP and SQL Containers are glued together by docker-compose. Every Compose container is reachable by its name defined in the docker-compose.yml file.
