### ISSUE TITLE
[BUG] docker-compose up -d 出现问题 构建问题

### ISSUE THREAD

**Issue by 287075872** [sprintcube/docker-compose-lamp#179]
**Describe the bug**

1. 运行 docker-compose up -d 

Cloning into 'imagick'... fatal: unable to access 'https://github.com/Imagick/imagick/': Failed to connect to github.com port 443: Connection refused ERROR: Service 'webserver' failed to build: The command '/bin/sh -c cd /usr/local/src &&     git clone https://github.com/Imagick/imagick &&     cd imagick &&     git checkout ${IMAGICK_COMMIT} &&     phpize &&     ./configure &&     make &&     make install &&     cd .. &&     rm -rf imagick &&     docker-php-ext-enable imagick' returned a non-zero code: 128

**which Branch / PHP Version are you using ?**
php74

**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Ubuntu]
 - Docker Version:
```
docker -v
Docker version 19.03.5, build 633a0ea
```
**Additional context**

**Comment by MrOffline77** [comment]
I'm not able to reproduce this issue. The php Container builds fine on my system. Please make sure you can reach github.
