### ISSUE TITLE
Virtual Hosts

### ISSUE THREAD

**Issue by ricardolmsilva** [sprintcube/docker-compose-lamp#18]
Hello, thank you for share your project with us.

Im trying to configure virtual hosts, but im with problems. I created 2 directories site1 and site2 inside www directory each one with a index.html inside. After that I was in virtual host config file and configured 2 virtual hosts.
Finally I raised my containers and tried access to the hosts, but it doesn't work and if I type localhost, it still working.

There it is.

![screen shot 2019-01-10 at 00 21 00](https://user-images.githubusercontent.com/34528668/50938114-b230a000-146e-11e9-92e4-46e4bdbae5f1.png)
![screen shot 2019-01-10 at 00 21 19](https://user-images.githubusercontent.com/34528668/50938122-bc529e80-146e-11e9-936a-bfcbe4000620.png)
![screen shot 2019-01-10 at 00 23 45](https://user-images.githubusercontent.com/34528668/50938131-c2e11600-146e-11e9-94da-dc10e32f64f3.png)
![screen shot 2019-01-10 at 00 24 50](https://user-images.githubusercontent.com/34528668/50938137-c6749d00-146e-11e9-8bc0-014e88edc7e5.png)
![screen shot 2019-01-10 at 00 33 34](https://user-images.githubusercontent.com/34528668/50938277-65999480-146f-11e9-8ff8-ce23dbb2be1d.png)

Hope you can help me.
Thank you.

Ricardo Silva

**Comment by narendravaghela** [comment]
You need to add host entries for these virtual hosts.

1. Open hosts file using `sudo nano /etc/hosts`.
2. Add following entries at the end of file and save.
```
127.0.0.1 site1.dev
127.0.0.1 site2.dev
```

**Comment by ricardolmsilva** [comment]
Thank you, it worked.

Just another question, why localhost still working  and open site1?

I know, or I think I know, localhost is always watching in port 80. But why open site1? It should be redirecting to root, that is www, right?

![image](https://user-images.githubusercontent.com/34528668/50976349-a46b3100-14e7-11e9-8614-d7939eabf0af.png)

**Comment by narendravaghela** [comment]
In most of the Operating Systems, the `localhost` is set to point to the 127.0.0.1 address. That's why it is working.
