### ISSUE TITLE
Importing database - container confusion

### ISSUE THREAD

**Issue by afarsh** [sprintcube/docker-compose-lamp#184]
I am a bit confused about the containers and I hope someone can clarify this. After running this 'docker-compose-lamp' image, the following containers are generated:

```
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS        PORTS                                      NAMES
88f7...   phpmyadmin/phpmyadmin   "/docker-entrypoint.…"   23 hours ago   Up 23 hours   0.0.0.0:8080->80/tcp                       lamp-phpmyadmin
dedb...   lamp_webserver          "docker-php-entrypoi…"   23 hours ago   Up 23 hours   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   lamp-php74
f1d6...   redis:latest            "docker-entrypoint.s…"   23 hours ago   Up 23 hours   127.0.0.1:6379->6379/tcp                   lamp-redis
05de...   lamp_database           "docker-entrypoint.s…"   23 hours ago   Up 23 hours   127.0.0.1:3306->3306/tcp                   lamp-mariadb106
```
I understand that if I want to do any MySQL commands I have to ssh into the one named 'lamp-mariadb106'. And this works. But from which container do I import a database dump to this place using mysql command. The database dump is placed in 'www' on the local machine which is mapped to '/var/www/html'

I guess my main confusion is how to know which container you need to ssh into to do various tasks?

Much grateful to anyone for clarifying this.

**Comment by MrOffline77** [comment]
You can reach the database from every listed container via the host `database`. Of course you need a mysql client too. 
You can import an sql dump directly through phpmyadmin, or inside the `lamp_webserver`with the mysql cli client. `mysql -u root -p'password' -h database`.
