### ISSUE TITLE
Laravel Project can't be used with this project

### ISSUE THREAD

**Issue by MahbbRah** [sprintcube/docker-compose-lamp#185]
**Describe the bug**
I was using a laravel project to set up with this docker container but unfortunately, I couldn't come up with a solution, tried all the stuff mentioned on the issues/solved list but still, it is not working

I set up laravel project in a subdirectory inside www dir. and the error I was getting is 
``
Forbidden

You don't have permission to access this resource.
Apache/2.4.38 (Debian) Server at localhost Port 80
``

**which Branch / PHP Version are you using ?**
php74

**Expected behavior**
I was expecting it to run fluently.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 used WSL backend
```
docker -v
Docker version 20.10.8, build 3967b7d
```

**Comment by MrOffline77** [comment]
Hi, this sounds like a problem with your directory structure or directory permissions. 
Please make sure the http config is pointing to your laravel public directory. 
This does not sound like a bug in the lamp stack.
