### ISSUE TITLE
Problem adding more hosts 

### ISSUE THREAD

**Issue by devope** [sprintcube/docker-compose-lamp#191]
I am running this stack on VDS.

1. At first I created **/config/vhosts/test.conf** 
```
<VirtualHost *:80>
        ServerAdmin mail@devope.ru
        ServerName test.767411-cc16406.tmweb.ru
        ServerAlias www.test.767411-cc16406.tmweb.ru
        DocumentRoot ${APACHE_DOCUMENT_ROOT}/test/
</VirtualHost>
```
2. Then I run `docker run lamp_webserver a2ensite test`
3. I get an error 
> ERROR: Site test does not exist!

Help me please, I'm learning this stuff, but don't know where to search info about my needs.
Thanks a lot, best wishes!

**Comment by MrOffline77** [comment]
Hi @devope,
this stack is build for local development only. I would suggest to take a look at the official Apache webserver documentation to tackle your specific problem.
