### ISSUE TITLE
How to modify the network name?

### ISSUE THREAD

**Issue by LoetLuemmel** [sprintcube/docker-compose-lamp#194]
**Describe the bug**
Well, less kind of bug, but more looking for a hint. - 
I try to modify the network name and so far couldn't find where 'lamp_default' is being set.

Could. someone please provide me with a hint?

Happy Hacking!

**Comment by MrOffline77** [comment]
Hi, 
this should be controlled by this variable in the env file: 
```
# To determine the name of your containers
COMPOSE_PROJECT_NAME=lamp
```

**Comment by LoetLuemmel** [comment]
Well, that‘s the problem: The network name is ‚default_lamp‘.
My .env file just says ‚lamp‘.

Could there be another spot?
