### ISSUE TITLE
Make it possible to configure database settings

### ISSUE THREAD

**Issue by aldexxx86** [sprintcube/docker-compose-lamp#199]
Make it possible to configure database settings that are usually found in the my.cnf file.
For example I would like to be able to set the following setting:
lower_case_table_names=0

**Comment by alainseys** [comment]
Hy @aldexxx86,

you can do this by adding a volume entry to the database service like eg:
`- ${MYSQL_INITDB_DIR-./config/initdb/config/my.cnf}:/etc/my.cnf` 

at the end of the volumes section you need to add a command to allow it to run it in sql_mode

`command: --sql_mode=""`

rebuild the image and you should be good to go

**Comment by alainseys** [comment]
@aldexxx86 

i have [added](https://github.com/sprintcube/docker-compose-lamp/pull/200) a pull request with a other approach
