### ISSUE TITLE
Can't access own database

### ISSUE THREAD

**Issue by kPentagramm** [sprintcube/docker-compose-lamp#204]
If I try to access the MariaDB via pdo with my own script in a subfolder of www, I always get error SQLSTATE[HY000] [2002] No such file or directory.
If I copy the script into the pdo-test-file it works fine.

**Comment by alainseys** [comment]
@kPentagramm 

Can you post your used code and the used php version and MariaDB version

**Comment by Timoffey** [comment]
The same thing. php74, mariadb106. When I do 
new PDO('mysql:host=localhost; dbname=dbname', 'root', 'root');
I have a Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory

**Comment by MrOffline77** [comment]
Ahoy everyone,
this should work
```
new PDO('mysql:host=database; dbname=dbname', 'root', 'root');
```
Please note here that the ``mysql:host`` is called ``database`` not ``localhost``, cause inside the docker-compose.yml we gave the container the name ``database``. To access the container from the webserver container via the linked loopback device you need to access it with its "Container Name", in this case ``database``. 
Let me know if this works for you.
