### ISSUE TITLE
[BUG] When using navigator to link the MySQL database, you will be prompted with 10061 error. The link cannot be made. How should this be handled?

### ISSUE THREAD

**Issue by Mibifinance** [sprintcube/docker-compose-lamp#213]
When using navigator to link the MySQL database, you will be prompted with 10061 error. The link cannot be made. How should this be handled?

**Comment by MrOffline77** [comment]
The MySQL Container is not exposed outside of the docker network. You need to modify the docker-compose.yml to change that. 
You could use the phpmyadmin instead. It comes preconfigured with the stack.
