### ISSUE TITLE
Additional container for reverse proxy and wordpress

### ISSUE THREAD

**Issue by omps** [sprintcube/docker-compose-lamp#215]
**PHP 7.4; Wordpress; Nginx**

**Addition of Containers**
add separate wordpress container and an nginx container and use nginx container as reverse proxy, 

**Internal ports will help inconsistent port mapping with localhost**
A reverse proxy because in which case we don't have to map the ports of all the internal containers to localhost and a single container can manage the request within the docker-compose file.

**Comment by arcanisgk** [comment]
Any example to do that???

**Comment by tarlepp** [comment]
Hmm, for wordpress why not just use "official" images - https://hub.docker.com/_/wordpress ?

**Comment by MrOffline77** [comment]
Hi, that is out of scope for this project. Therefore I will close this issue.
