### ISSUE TITLE
[BUG] can depploy  php81 server

### ISSUE THREAD

**Issue by arcanisgk** [sprintcube/docker-compose-lamp#219]
after trying to settup my enviroment i get this error:

------
 > [lamp-webserver  2/13] RUN apt-get -y update --fix-missing &&     apt-get upgrade -y &&     apt-get --no-install-recommends install -y apt-utils &&     rm -rf /var/lib/apt/lists/*:
#0 0.943 Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
#0 1.675 Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
#0 1.947 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
#0 2.267 Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
#0 15.45 Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [378 kB]
#0 45.73 Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [378 kB]
#0 46.97 Fetched 8509 kB in 47s (183 kB/s)
#0 46.97 Reading package lists...
#0 47.43 W: http://deb.debian.org/debian-security/dists/buster/updates/main/binary-amd64/by-hash/SHA256/eb5c087b0af66d4a71d4d0853d7687b1412f26d4fe8874d9aa36a478f6f9a789: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
#0 47.44 Reading package lists...
#0 47.91 Building dependency tree...
#0 48.01 Reading state information...
#0 48.02 Calculating upgrade...
#0 48.15 The following packages will be upgraded:
#0 48.15   libc-bin libc-dev-bin libc6 libc6-dev
#0 48.37 4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#0 48.37 Need to get 6631 kB of archives.
#0 48.37 After this operation, 2048 B of additional disk space will be used.
#0 48.37 Get:1 http://deb.debian.org/debian-security buster/updates/main amd64 libc6-dev amd64 2.28-10+deb10u2 [2693 kB]
#0 221.6 Get:2 http://deb.debian.org/debian-security buster/updates/main amd64 libc-dev-bin amd64 2.28-10+deb10u2 [276 kB]
#0 285.5 Get:3 http://deb.debian.org/debian-security buster/updates/main amd64 libc6 amd64 2.28-10+deb10u2 [2869 kB]
#0 520.5 Err:3 http://deb.debian.org/debian-security buster/updates/main amd64 libc6 amd64 2.28-10+deb10u2
#0 520.5   Connection failed [IP: 146.75.38.132 80]
#0 520.7 Get:4 http://deb.debian.org/debian-security buster/updates/main amd64 libc-bin amd64 2.28-10+deb10u2 [793 kB]
#0 706.1 Get:4 http://deb.debian.org/debian-security buster/updates/main amd64 libc-bin amd64 2.28-10+deb10u2 [793 kB]
#0 706.2 E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/g/glibc/libc6_2.28-10+deb10u2_amd64.deb  Connection failed [IP: 146.75.38.132 80]Fetched 3053 kB in 10min 58s (4639 B/s)
#0 706.2
#0 706.2 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
 >#failed to solve: executor failed running [/bin/sh -c apt-get -y update --fix-missing &&     apt-get upgrade -y &&     apt-get --#no-install-recommends install -y apt-utils &&     rm -rf /var/lib/apt/lists/*]: exit code: 100

**Comment by MrOffline77** [comment]
Looks like you have problems connecting to the upstream mirror from debian so the container can build correct.
