### ISSUE TITLE
Warning: mysqli_connect(): Server sent charset (255) unknown to the client

### ISSUE THREAD

**Issue by mjepps72** [sprintcube/docker-compose-lamp#222]
Just trying to get the sample via the readme running and having an issue with mysqli_connect charset. I don't see a configuration entry for changing this. Do you have any suggestions? 

![image](https://user-images.githubusercontent.com/1972208/199365741-4242c15d-b874-44ea-bc57-f339e60c3ac9.png)

**Comment by leberman** [comment]
Please give us a little bit more information. Especially the docker container logs.
More infos about docker logs: https://docs.docker.com/engine/reference/commandline/logs/

**Comment by MrOffline77** [comment]
No update from issue creator - close.

**Comment by grzegorzmanda** [comment]
When using PHP 5.6  one needs to add in a piece below to docker-compose  (_database_ section)
`
command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
`
or modify the _mysql57_ dockerfile with default character set and collation parameters.
Otherwise - the error as above will show up.

Hope that helps.
