### ISSUE TITLE
SugarCRM dies after quick repair

### ISSUE THREAD

**Issue by Dlogon** [sprintcube/docker-compose-lamp#223]
Hi

I don´t know if there is the place where I should put this.

I have an instance of SugarCRM, this instance is big, has a lot of customizations. 
I try this beautiful repo, and the instance works after some changes like permissions into folder: I was having this problem
https://sugarclub.sugarcrm.com/dev-club/f/questions-answers/544/loading-displaying-on-screen-nothing-display-after-that-not-even-login-screen.
So the instance was working good after the fix of the permisions, but after a "quick repair and rebuild" (Operation that generates and caches some files in sugarcrm) the instance dies, I can not login anymore for a problem with a request

![image](https://user-images.githubusercontent.com/26014056/200728812-f45fd62b-ee8d-4be2-9b51-5ed3eea29bcc.png)

I debug it with xdebug and it gives me some typical errors from sugar, the only difference was that the bcadd function is undefined, although bcmath is installed.

I try too this repo https://github.com/esimonetti/SugarDockerized, but with this, I can not pass the loading... screen.

The most impressive thing for me is that with windows and wamp it works perfectly, without any extra configurations( the above options were used in ubuntu)

**which Branch / PHP Version are you using ?**
php74

**Steps to reproduce**

1. copy SugarCRM instance
2. do a quick repair of sugarCRM

**Expected behavior**
Recreate and cache sugarCRM files

**Desktop (please complete the following information):**
 - Ubuntu 20.04.4 LTS
 - Chrome
 - Docker Version:
```
docker -v
Docker version 20.10.17, build 100c701
```

**Comment by MrOffline77** [comment]
Hi, this does not look like a issue with the software here :). So since this issue is out of scope I will close this issue.
