### ISSUE TITLE
[BUG] I do not understand how to make not localhost, but access from the Internet

### ISSUE THREAD

**Issue by mrranger** [sprintcube/docker-compose-lamp#226]
If I use mysql, then it works locally, I install laravel, but if I want to go to phpmyadmin, mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'172.25.0.4' (using password: YES)
But if I put host in laravel: mysql container name I can login but laravel can't connect to bd

**Comment by rbahala** [comment]
Thank you for your reply. I got it to work by reinstalling everything from
scratch including Docker.
