### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by smilemittal** [sprintcube/docker-compose-lamp#229]
I have installed multiple PHP versions setup and using parallelly. It's working perfectly fine. Now I want to set up webhook requests in my project, I have installed a local tunnel in docker PHP 8, but it is going to redirect docker PHP 74. I did not understand why. 

added code in docker file
```
# Install npm
RUN curl --silent --location https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs 
RUN echo "Node: " && node -v
RUN echo "NPM: " && npm -v
RUN npm install -g localtunnel
```

Running a command in the docker container
` lt --port 80`

All changes are done in cc-lamp-php8.

But still, it is redirected to a site hosted for php74.

Can you please help me? 

![image](https://user-images.githubusercontent.com/13959872/211260933-794cdcc0-77ca-454b-ac9d-a80e177ddf59.png)

Thanks

**Comment by boelle** [comment]
maybe provide a title to the bug report?

**Comment by MrOffline77** [comment]
Hey there, this is not directly related to code of the stack itself, So I will close this issue.
