### ISSUE TITLE
Access to paret folder

### ISSUE THREAD

**Issue by Machacek76** [sprintcube/docker-compose-lamp#23]
Hi how to including php files from parent subfolders. I must include ../src/bootstrap.php  in index.php 

- www/index.php
- src/bootstrap.php
- vendor/...
...
...
...

`<VirtualHost *:80>`
`    ServerAdmin webmaster@localhost`
`    DocumentRoot "/var/www/html/www"`
`    ServerName localhost`
`	<Directory "/var/www/html/">`
`		AllowOverride all`
`	</Directory>`
`</VirtualHost>`

`    volumes: `
`      - ${DOCUMENT_ROOT-./www}:/var/www/html`
`      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini`
`      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled`
`      - ${LOG_DIR-./logs/apache2}:/var/log/apache2`

Error:
Warning: require(/var/www/html/../src/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 10

**Comment by narendravaghela** [comment]
Hello @Machacek76 

The current setup is configured to sync the default www root directory with the host machine. So, you can update your project directory structure in a way that you `index.php` file and `src` directory are on the same level.

Consider the below directory structure of your project on the host machine, and let's say your path to the directory is `/home/username/projects`

* /home/username/projects/
  * src
  * vendor
  - other dirs and files
  - your-project-dir
    - index.php
    - other files and dirs

Now, sync this {path-to-dir} with document root on docker by setting it in .env file. For example,
```
DOCUMENT_ROOT=/home/username/projects
```
So, everything under `/home/username/projects` will be in sync with docker's `/var/www/html` directory. And now you can update the default virtual host to point to `/var/www/html/your-project-dir`.

**Comment by Machacek76** [comment]
Hello **@narendravaghela**
it's working,
thank you for help

**Comment by narendravaghela** [comment]
Glad to know it's working!
