### ISSUE TITLE
[BUG] Compose file is invalid because of services.phpmyadmin.ports

### ISSUE THREAD

**Issue by HorselessName** [sprintcube/docker-compose-lamp#231]
Hello. I followed all the steps provided, and when running docker-compose up I got the following error:

WARNING: The HOST_MACHINE_UNSECURE_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The HOST_MACHINE_PMA_PORT variable is not set. Defaulting to a blank string.
WARNING: The HOST_MACHINE_PMA_SECURE_PORT variable is not set. Defaulting to a blank string.
WARNING: The HOST_MACHINE_REDIS_PORT variable is not set. Defaulting to a blank string.

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.phpmyadmin.ports contains an invalid type, it should be a number, or an object
services.phpmyadmin.ports contains an invalid type, it should be a number, or an object
services.webserver.ports contains an invalid type, it should be a number, or an object

**Comment by FalaiTio** [comment]
same here

**Comment by MrOffline77** [comment]
Hi looks like your env was not present. 
The second error is a different thing. That will be addressed here: #235
