### ISSUE TITLE
[BUG] Building php54 container

### ISSUE THREAD

**Issue by nevick** [sprintcube/docker-compose-lamp#235]
**Describe the bug**

I try to build container with php54 but can`t do it because i get the error: 

=> ERROR [ 4/13] RUN apt-get -y --allow-unauthenticated update && apt-get upgrade -y --allow-unauthenticated                                                                           15.8s
------
 > [ 4/13] RUN apt-get -y --allow-unauthenticated update && apt-get upgrade -y --allow-unauthenticated:
#0 6.578 Ign http://security.debian.org jessie/updates InRelease
#0 6.605 Ign http://archive.debian.org jessie InRelease
#0 6.613 Ign http://security.debian.org jessie/updates Release.gpg
#0 6.644 Get:1 http://archive.debian.org jessie Release.gpg [2420 B]
#0 6.646 Ign http://security.debian.org jessie/updates Release
#0 6.683 Get:2 http://archive.debian.org jessie Release [148 kB]
#0 9.811 Ign http://archive.debian.org jessie Release
#0 9.847 Get:3 http://archive.debian.org jessie/main Sources [9169 kB]
#0 9.946 Err http://security.debian.org jessie/updates/main Sources
#0 9.946   404  Not Found [IP: 151.101.130.132 80]
#0 10.00 Err http://security.debian.org jessie/updates/main amd64 Packages
#0 10.00   404  Not Found [IP: 151.101.130.132 80]
#0 13.73 Get:4 http://archive.debian.org jessie/main amd64 Packages [9098 kB]
#0 15.21 W: GPG error: http://archive.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1587841717
#0 15.21 W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/source/Sources  404  Not Found [IP: 151.101.130.132 80]
#0 15.21 
#0 15.21 W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.130.132 80]
#0 15.21 
#0 15.21 E: Some index files failed to download. They have been ignored, or old ones used instead.
#0 15.21 Fetched 18.4 MB in 8s (2113 kB/s)
------
Dockerfile:13
--------------------
  11 |         printf "deb-src http://security.debian.org jessie/updates main" >>  /etc/apt/sources.list
  12 |     
  13 | >>> RUN apt-get -y --allow-unauthenticated update && apt-get upgrade -y --allow-unauthenticated
  14 |     
  15 |     # Install tools && libraries
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -y --allow-unauthenticated update && apt-get upgrade -y --allow-unauthenticated" did not complete successfully: exit code: 100
ERROR: Service 'webserver' failed to build : Build failed

**which Branch / PHP Version are you using ?**
php54

**Steps to reproduce**
1. Go to  .env file
2. Set PHPVERSION=php54
3. Build container:  docker-compose up -d --build
4. Got error: ERROR: Service 'webserver' failed to build : Build failed

**Expected behavior**
i want to get the php54 container

**Screenshots**

![issue](https://user-images.githubusercontent.com/24686304/231811708-a3b2e584-30f1-44ce-8e19-8ab9d1c13708.jpg)

**Desktop (please complete the following information):**
 - OS:  Linux Debian11 
 - Browser: chrome
 - Docker Version: Docker version 23.0.3, build 3e7cbfd
```

**Comment by Kasui92** [comment]
@nevick 

I ran into the same problem and with a bit of searching I found [this](https://stackoverflow.com/a/75878537).

So I made this change:

```
# Fix the source.list for jessie
RUN printf "deb http://archive.debian.org/debian/ jessie main\n" > /etc/apt/sources.list && \
    printf "deb-src http://archive.debian.org/debian/ jessie main\n" >>  /etc/apt/sources.list && \
    printf "deb **http://archive.debian.org/debian-security** jessie/updates main\n" >>  /etc/apt/sources.list && \
    printf "deb-src **http://archive.debian.org/debian-security** jessie/updates main" >>  /etc/apt/sources.list
```

and it actually doesn't give me the error anymore, however it takes a really long time to build the image.

**Comment by Kasui92** [comment]
The same issue also affects the php:5.6-apache image, based on debian stretch.

Again, it's all in the archives.

**Comment by MrOffline77** [comment]
I will provide a patch in the next days to address this. Thanks everyone for digging into that.

**Comment by MrOffline77** [comment]
Fix is available in master branch. I will close this issue now. Please reopen if it doesn't work for you :).
