### ISSUE TITLE
[BUG] The default ini file is not used

### ISSUE THREAD

**Issue by mdprasadeng** [sprintcube/docker-compose-lamp#236]
On the default installation the ini file from .config/php.ini is not used by the lamp server.

.config/php.ini is copied to the docker volume and is available at `/usr/local/etc/php/php.ini` 
but the phpinfo shows that file picked up is from `/var/www/html/php.ini`

**which Branch / PHP Version are you using ?**
php81

**Comment by MrOffline77** [comment]
Hi, I just build a fresh container for php81. Im not able to reproduce what you are reporting. Can you give us some more details on your setup ? 
In general this should wor
<img width="946" alt="Bildschirmfoto 2023-04-26 um 11 26 20" src="https://user-images.githubusercontent.com/43014876/234533489-ed67f478-c42d-49d0-985e-fe31e3f41424.png">
k out of the box. See screenshot attached.
