### ISSUE TITLE
directory permissions

### ISSUE THREAD

**Issue by developersingh** [sprintcube/docker-compose-lamp#24]
hi, I have added the following command at the end of webserver dockerfile
RUN chown -R www-data:www-data /var/www/html
but the owner of /var/www/html/ is still root.

I am running docker on windows 10.

I have copied my application ( which is in laravel) under /var/www/html folder and the login page does come but after the post it gives 419 error. After some research, I figured out that owner of /var/www/html should be www-data. and I am not able to change the owner. please help.

log from apache AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Thu Apr 18 13:00:59.307872 2019] [core:warn] [pid 6] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Thu Apr 18 13:00:59.311491 2019] [mpm_prefork:notice] [pid 6] AH00163: Apache/2.4.25 (Debian) PHP/7.1.20 configured -- resuming normal operations
[Thu Apr 18 13:00:59.312169 2019] [core:notice] [pid 6] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

and

<title>404 Not Found</title>
Not Found
The requested URL /svg/403.svg was not found on this server.

Apache/2.4.25 (Debian) Server at www.localhost Port 80
is the error on browser.

**Comment by narendravaghela** [comment]
@developersingh
If you see, the error says /svg/403.svg. This is not related to permission. Can you please verify the URL generation in your laravel application or the directory path in your virtual host?

**Comment by developersingh** [comment]
DOCUMENT_ROOT=./www
VHOSTS_DIR=./config/vhosts
APACHE_LOG_DIR=./logs/apache2
PHP_INI=./config/php/php.ini
MYSQL_DATA_DIR=./data/mysql
MYSQL_LOG_DIR=./logs/mysql

are same in sample.env

**Comment by developersingh** [comment]
https://stackoverflow.com/questions/18724718/error-403-in-loading-resources-like-css-and-js-in-my-index-php suggests that Tip: I usually make the apache/nginx's user group owner of that kind of folders and give 775 permission to it.

And I am not able to do that.

**Comment by narendravaghela** [comment]
Are you running your laravel app in sub directory or root directory?
Regarding the permission, you need to check with the host machine as well. On which OS are you running this stack?

**Comment by developersingh** [comment]
windows 10

laravel app /var/www/html/feeapp directory

**Comment by narendravaghela** [comment]
Try to create a new virtual host which points to `/var/www/html/feeapp` directory.
See `./config/vhosts` for reference.

**Comment by developersingh** [comment]
still  419 error
Sorry, your session has expired. Please refresh and try again.

**Comment by developersingh** [comment]
why is chown command not working?

**Comment by narendravaghela** [comment]
Is this solved? Please reopen if there are still issues, and also try to use the latest builds.
