### ISSUE TITLE
[FEATURE] Securing phpMyAdmin Instance

### ISSUE THREAD

**Issue by derickmgezi** [sprintcube/docker-compose-lamp#242]
Because of its ubiquity, phpMyAdmin is a popular target for attackers, and it is recommended to take extra care to prevent unauthorized access. 

Requesting for a feature that will secure the phpMyAdmin instance by placing a gateway in front of the entire application by using Apache’s built-in **.htaccess authentication and authorization functionalities,** that prompts for authorization before accessing phpMyAdmin application as seen below.
<img width="265" alt="image" src="https://github.com/sprintcube/docker-compose-lamp/assets/7348140/15b08136-def5-44a4-8a13-1e27545cdece">

**Comment by theking2** [comment]
Indeed I don't think putting PhpMyAdmin in the wild. are there any examples of breaches?

**Comment by derickmgezi** [comment]
> Indeed I don't think putting PhpMyAdmin in the wild. are there any examples of breaches?

Not that I know of, but with all my LAMP setups I usually protect my phpMyAdmin with an extra authentication layer before exposing it to the internet. This [link ](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-20-04) explains how Secure phpMyAdmin and I was hoping this feature could be incorporated this LAMP stack.

**Comment by theking2** [comment]
Ok but you are using docker as a production environment? That seems odd.

----------------------------------------

3 jun. 2023 20:07:51 derickmgezi ***@***.***>:

**Comment by derickmgezi** [comment]
> Ok but you are using docker as a production environment? That seems odd.

Well at the moment I'm not using Docker, but I am in a process of deploying all my applications with Docker since it will help reduce time spent with administration tasks especially in resolving new vulnerabilities on OS or Application Level.

I have made several tweaks with this Docker-compose-lamp image to best fit my application needs, but I'm missing a feature that protects phpMyAdmin including an additional authentication layer when exposed to the Internet. I was hoping it could be included in this DOCKER-COMPOSE-LAMP image.

I will appreciate any ideas that I might also use as a work around.

**Comment by danyalsakhibhatti** [comment]
@theking2 kindly recommend what could be used instead of docker in production env.

**Comment by MrOffline77** [comment]
Please take a look at #260 there is a way describe to change this behavior. 
Please keep also in mind that this stack is build for local development, not for production usage :).
