### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by sashuu6** [sprintcube/docker-compose-lamp#25]
I download the branch 7.2 and docker-compose up it.
But, I cannot access database. Can't open PHPMyaadmin.
Everywhere I am getting the error:-

Warning:  mysqli_connect(): (HY000/1045): Access denied for user  'root'@'172.28.0.3' (using password: YES) in /var/www/html/index.php on  line 34
--

MySQL connecttion failed: Access denied for user 'root'@'172.28.0.3' (using password: YES)

**Comment by narendravaghela** [comment]
Check two things:
1. Make sure the phpmyadmin container is running.
2. You need to pass `mysql` as a hostname instead of `localhost`

**Comment by sashuu6** [comment]
Can you explain in detail please? I am just a novice in docker.

**Comment by theonlyakhil** [comment]
> Check two things:
> 
> 1. Make sure the phpmyadmin container is running.
> 2. You need to pass `mysql` as a hostname instead of `localhost`

The phpmyadmin container is working just fine.
I have done everything correct

**Comment by sashuu6** [comment]
I have fixed the error. Thank you
