### ISSUE TITLE
2 php versions in same apache container

### ISSUE THREAD

**Issue by djarnoldmx** [sprintcube/docker-compose-lamp#250]
Hello 
Will it be possible to have 2 versions of PHP at the same time without having to install another Apache?
I have my lamp_webserver running php 7.4 but i need to run at the same time for some projects php 8.1 using the same www folder and the same apache version of the container.

Could you help me how to do it?

**Comment by MrOffline77** [comment]
Hi @djarnoldmx 
this is not possible due to the design of the stack. Technically this is possible in general, but not with how the stack is build as of today.
