### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by teolando** [sprintcube/docker-compose-lamp#251]
I'm trying to make a .htaccess RewriteRule and the AllowOverride is always "none" and a get error "Internal error server" 

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.38 (Debian) Server at localhost Port 80"

Mysql Version is 5.7, PHP 7.4

Do we have a quick fix for this? 

When i change the apache2.conf and restart doesn't work. 

My .htaccess rule:

"RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [NC, L]"

Sincerely Theo

**Comment by MrOffline77** [comment]
Hi theo, 
sorry for the late response. I assume this is a apache topic than a topic of the stack itself. I will close this ticket therefore.
Please feel free to reopen if I'm wrong.

**Comment by teolando** [comment]
Yeah, i've fixed with a rule in .htaccess.
