### ISSUE TITLE
[BUG] Odd slow for app? Cant find logs

### ISSUE THREAD

**Issue by killmasta93** [sprintcube/docker-compose-lamp#255]
**Describe the bug**
Hi
Currently we have an odd issue as the app it self is really slow, i was thinking it was the host itself but i have other sites working well,
I was trying to troubleshoot but cant seem to find the logs of php or php-fpm any ideas where i can find it?

**which Branch / PHP Version are you using ?**
php8.1

Thank you

**Comment by MrOffline77** [comment]
Hi, you could check the logs of the php container itself [with docker logs <containerid>. ](https://docs.docker.com/engine/reference/commandline/container_logs/)

**Comment by killmasta93** [comment]
Thanks for the reply, at the end it seems that it was an issue with the app itself
