### ISSUE TITLE
PHPMYADMIN AUTO LOGIN

### ISSUE THREAD

**Issue by sajal7866** [sprintcube/docker-compose-lamp#260]
**Describe the bug**
I am using ubuntu 22 and phpmyadmin getting auto login from any browser it's not asking for the username and password.

**which Branch / PHP Version are you using ?**
php8.2

**Steps to reproduce**
Just install it on the ubuntu server and open the PHPMYADMIN

**Comment by Grahon** [comment]
@sajal7866  - just comment in docker-compose file PMA_USER and PMA_PASSWORD in environment section.
It will disable auto login for PHPMYADMIN

**Comment by sajal7866** [comment]
@Grahon  thanks for reply i will check it and thanks for this beautiful setup. i am making a GUI based auto deployment with your setup

**Comment by MrOffline77** [comment]
Hey there,
the stack is developed with focus for local development on you machine. The comes up from time to time, but the current opinion is that a auto login is more convenient on a local machine.
