### ISSUE TITLE
[BUG] failed to solve: process "/bin/sh -c apt-get -y update --fix-missing" did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by gmaccario** [sprintcube/docker-compose-lamp#261]
**Describe the bug**

I run **_docker-compose up -d_** on PHPVERSION=php71 (but also 7.2, 7.3) and I get these errors: 

------
==> ERROR [webserver  2/29] RUN apt-get -y update --fix-missing                                                                                                                                             1.9s
 > [webserver  2/29] RUN apt-get -y update --fix-missing:
1.015 Ign http://security.debian.org jessie/updates InRelease
1.065 Ign http://deb.debian.org jessie InRelease
1.071 Ign http://security.debian.org jessie/updates Release.gpg
1.116 Ign http://security.debian.org jessie/updates Release
1.123 Ign http://deb.debian.org jessie Release.gpg
1.160 Ign http://deb.debian.org jessie Release
1.169 Err http://security.debian.org jessie/updates/main amd64 Packages
1.169
1.205 Err http://deb.debian.org jessie/main amd64 Packages
1.205
1.218 Err http://security.debian.org jessie/updates/main amd64 Packages
1.218
1.250 Err http://deb.debian.org jessie/main amd64 Packages
1.250
1.262 Err http://security.debian.org jessie/updates/main amd64 Packages
1.262
1.290 Err http://deb.debian.org jessie/main amd64 Packages
1.290
1.310 Err http://security.debian.org jessie/updates/main amd64 Packages
1.310
1.333 Err http://deb.debian.org jessie/main amd64 Packages
1.333
1.370 Err http://security.debian.org jessie/updates/main amd64 Packages
1.370   404  Not Found [IP: 151.101.194.132 80]
1.376 Err http://deb.debian.org jessie/main amd64 Packages
1.376   404  Not Found [IP: 199.232.150.132 80]
1.377 W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/main/binary-amd64/Packages  404  Not Found [IP: 151.101.194.132 80]
1.377
1.377 W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 199.232.150.132 80]
1.377
1.377 E: Some index files failed to download. They have been ignored, or old ones used instead.

failed to solve: process "/bin/sh -c apt-get -y update --fix-missing" did not complete successfully: exit code: 100
------

**which Branch / PHP Version are you using ?**
php71, php72, php73

**Steps to reproduce**
1. Create a .env file
2. Change the PHP version to php71
3. Run docker-compose up -d
4. See errors

**Expected behavior**
I am expecting to run the containers, as per php8

**Screenshots**
![image](https://github.com/sprintcube/docker-compose-lamp/assets/5927739/c8d58925-9797-46df-ba71-29b6946cfcf9)

**Desktop (please complete the following information):**
 - Docker version 24.0.7, build afdd53b

**Additional context**
Working correctly for PHP8 though.

**Comment by cjlovescoffee** [comment]
I had the same issue with the 5.6 branch. I fixed it by adding:

```
RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
```

before

```
RUN apt-get -y update....
```

The reason is that stretch (and jessie, not sure which you're on because the log you pasted and your screenshot seem to show both) has been archived, so you need to update the sources list to use the archive location. Hope this helps, I guess the repo should be updated to make sure the archive locations are added to the appropriate Dockerfiles.

**Comment by MrOffline77** [comment]
Hey everyone, 
i just pushed a fix for that. Thanks for reporting. 
[8140d5b](https://github.com/sprintcube/docker-compose-lamp/commit/8140d5bd686c9cdacf5d03d83f6ec0fff5c2546d)
