### ISSUE TITLE
PHPMyAdmin

### ISSUE THREAD

**Issue by Zibulon** [sprintcube/docker-compose-lamp#28]
I tried to connect by default credentials root/tiger, but have this problem:
 
Cannot log in to the MySQL server

mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
 mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

**Comment by pin147** [comment]
Instead of `localhost` use `mysql`. Yes, it's weird but heh.
I had the same problem when I tried to install WP.

**Comment by KappaDistributive** [comment]
@pin147 Can you elaborate? I have the same problem as Zibulon but don't know what you mean by 'using mysql'.

**Comment by narendravaghela** [comment]
@KappaDistributive 
It's a hostname of MySQL server. See the following example,

```php
<?php
$link = mysqli_connect("mysql", "root", "tiger", null);
if (!$link) {
    echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}
echo "Success: A proper connection to MySQL was made! The docker database is great." . PHP_EOL;
echo "Host information: " . mysqli_get_host_info($link) . PHP_EOL;
mysqli_close($link);
```

See the connection function, we are passing `mysql` as a first parameter and that is a hostname. Generally, we use `localhost` for most of the cases, but in this case, it is different.
