### ISSUE TITLE
PHP and MySQL versions don't change

### ISSUE THREAD

**Issue by rebroff** [sprintcube/docker-compose-lamp#282]
**Describe the bug**
1) change .env
2) `docker compose up -d`
![Снимок 28 06 2024 в 18 07](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/21b4d7a8-15cc-4e21-83f8-4be79af507db)

4)
 ![Снимок 28 06 2024 в 18 09](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/ce8e7bd5-a6df-4944-a284-d68c829a4d50)

5)
![Снимок 28 06 2024 в 18 09 (1)](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/850289e3-6761-41c5-a5c0-45713da453de)

**Comment by MrOffline77** [comment]
Please try to rebuild the container

`docker-compose build --no-cache`

**Comment by devrodor** [comment]
As suggested, try rebuilding with

docker-compose up -d --build

**Comment by rebroff** [comment]
Same result for both command
![Снимок 28 06 2024 в 18 39](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/c10150ed-9630-49dc-8f9b-efe8258b4e3a)

**Comment by rebroff** [comment]
> As suggested, try rebuilding with
> 
> docker-compose up -d --build

This command successfully changes php version. 
But there is a problem with MySQL.

**Comment by devrodor** [comment]
If you are on macOS, you must use MariaDB. MySQL is not compatible with Apple Silicon, as noted in .yaml file. Is this perhaps your scenario?

**Comment by rebroff** [comment]
> If you are on macOS, you must use MariaDB. MySQL is not compatible with Apple Silicon, as noted in .yaml file. Is this perhaps your scenario?

Yes, I am.

**Comment by rebroff** [comment]
> If you are on macOS, you must use MariaDB. MySQL is not compatible with Apple Silicon, as noted in .yaml file. Is this perhaps your scenario?

Yes, I am.
