### ISSUE TITLE
I can't connect to the database via terminal

### ISSUE THREAD

**Issue by rebroff** [sprintcube/docker-compose-lamp#283]
I can't connect to the database via terminal
![Снимок 29 06 2024 в 14 36](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/c94bceb1-eac8-4a06-9217-2f11d493f307)

at the same time there is access to the mysql instance
![Снимок 29 06 2024 в 14 38](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/77e54608-1e61-4948-bcbe-43fac5ec25f8)

**Comment by MrOffline77** [comment]
You need to connect to the host „database“ its the container name of the database. Please see the example php connect referenced in index.php

https://github.com/sprintcube/docker-compose-lamp/blob/master/www/test_db.php

**Comment by rebroff** [comment]
> You need to connect to the host „database“ its the container name of the database. Please see the example php connect referenced in index.php
> 
> https://github.com/sprintcube/docker-compose-lamp/blob/master/www/test_db.php

Thanks for the help
