### ISSUE TITLE
Not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by batisuoc** [sprintcube/docker-compose-lamp#29]
- When i installed all container and started lamp server , in database connection in php file it show the connection error : 
"Error: Unable to connect to MySQL. Debugging errno: 1130 Debugging error: Host '172.24.0.4' is not allowed to connect to this MySQL server"
- In phpmyadmin when i try to log in and it show the same error : 
"mysqli_real_connect(): (HY000/1130): Host '172.24.0.4' is not allowed to connect to this MySQL server"

It is the ip address problem or not ?

**Comment by wi1w** [comment]
Hi.
For connecting to db you need use container name. In this case is mysql instead ip adress
