### ISSUE TITLE
No PMA configured

### ISSUE THREAD

**Issue by rikipm** [sprintcube/docker-compose-lamp#31]
I pull repository, set my config, call `docker-compose up -d` command, go to phpmyadmin and see error 

```
The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated. To find out why click here.
```

Problem is 

```
PMA Database ... not OK [ Documentation ]
General relation features Disabled
```

I googled and find what script `phpmyadmin\sql\create_tables.sql` file from phpmyadmin directory must be launched to create pma database. I tried to launch from TTY of phpmyadmin container, but it dont have mysql installed. 
I tried to import this file from phpmyadmin web-interface, but user "docker" dont have permission to do this. 
I cant sign out and login as root because "exit" button dont work. (I immediately login as docker after sign out) (`$cfg['Servers'][$i]['auth_type']` is `cookie`, i checked).
And I cant connect to mysql server with HeidiSQL from host system with localhost:3306.

**Comment by rikipm** [comment]
I solved this issue by giving "docker" user root permission through php and imported `phpmyadmin\sql\create_tables.sql`. It works, but I think it wrong decisionm I still cant login as root in phpmyadmin

**Comment by MrOffline77** [comment]
Hi @rikipm is this still a problem ? Does this still occur when you pull a fresh clone of the repo ?

**Comment by rikipm** [comment]
> Hi @rikipm is this still a problem ? Does this still occur when you pull a fresh clone of the repo ?

Hi. Yes, its still a problem.

1) Cant logout from phpmyadmin
2) Cant create pmadb

**Comment by MrOffline77** [comment]
Thank you. What PHP Version branch are you using ? I want to take a look at the code if the phpmyadmin is broken in your branch.

**Comment by rikipm** [comment]
> Thank you. What PHP Version branch are you using ? I want to take a look at the code if the phpmyadmin is broken in your branch.

7.3.x

**Comment by rikipm** [comment]
I solved this issue, and also solved security problem due to which any user can get access to phpmyadmin without auth. See details in #51
