### ISSUE TITLE
PHP 5.4 branch

### ISSUE THREAD

**Issue by fdbiondi** [sprintcube/docker-compose-lamp#36]
Hi! I like to send you a pull request for a new branch with php 5.4 version.
In order to do the PR I would need you to create the new branch 5.4.x.

Thanks.

**Comment by narendravaghela** [comment]
Is there any specific need for this? PHP 5.4 is too old now!

**Comment by narendravaghela** [comment]
Hi @fdbiondi 
I have created a branch named 5.4.x for you. You can submit the PR.
Thanks

**Comment by fdbiondi** [comment]
Hi @sprintcube, I was very busy lately and I can't awnser you. 
Thanks!
