### ISSUE TITLE
Connecting to SSL

### ISSUE THREAD

**Issue by therealrobbo** [sprintcube/docker-compose-lamp#40]
Running this container, I can access the site via http://localhost

However, when I try to connect via https://localhost:443 the browser throws a:
```
This site can’t be reached 
localhost unexpectedly closed the connection.
```

I tried adding some code to generate a self-signed certificate in the DockerFile and the following in /config/vhosts/default.conf, but nothing seems to work. 
```
<VirtualHost *:443>
    ServerAdmin webmaster@localhost
    ServerAlias localhost
    DocumentRoot "/var/www/html"
    ServerName localhost
	<Directory "/var/www/html/">
		AllowOverride all
	</Directory>

    SSLEngine on
	SSLCertificateFile	/etc/ssl/certs/generated.crt
	SSLCertificateKeyFile /etc/ssl/private/generated.key
</VirtualHost>
```

Can you provide any pointers?

**Comment by MrOffline77** [comment]
Did you restart the docker-compose containers so apache can perform a reload ? 
Are there any useful hints in the logs `./var/apache2/*` ? 
Permissions on cert file are correct ?

**Comment by therealrobbo** [comment]
Turns out I had to add these lines to the end of the DockerFile:

```
RUN a2ensite default-ssl
RUN a2enmod ssl
```

**Comment by c42759** [comment]
Can this be added to the repository by default?

**Comment by bharatpatil** [comment]
I'm currently working on this. Please refer #68
