### ISSUE TITLE
Don't have permission on Ubuntu 18

### ISSUE THREAD

**Issue by DandeSuen** [sprintcube/docker-compose-lamp#41]
Forbidden
You don't have permission to access / on this server.
Server unable to read htaccess file, denying access to be safe
Apache/2.4.25 (Debian) Server at localhost Port 80

I test some php-apache image on Ubuntu18.04, All the same.
And test two "docker-compose.yml" on Ubuntu18.04, All the same too.

**Comment by DandeSuen** [comment]
Add RUN usermod -u 1000 www-data && usermod -G staff www-data
RUN chown www-data:www-data /var/www/html
RUN chmod -R 777 /var/www/html/ to the .\bin\webserver\Dockerfile file. Still don't have permissions.

**Comment by MrOffline77** [comment]
Did you changed the volume mapping paths for the document root ? 
Usually this error indicates an empty or incorrect doc root. 
You can try to exec into the container an make sure your files are present in the document root.

**Comment by rhyseli** [comment]
I'm having the same issue. All values are default and correct doc root

**Comment by rhyseli** [comment]
Turns out it's because I was using WSL docker-compose with a standard Docker for Windows installation. Docker for Windows requires extra permissions to mount the filesystem.

Works fine if run from cmd or powershell.
