### ISSUE TITLE
Create a virtual host

### ISSUE THREAD

**Issue by hungfhq** [sprintcube/docker-compose-lamp#49]
below are the steps to create a new virtual host.

1. Edit the file - docker-compose-lamp/config/vhosts/default.conf or Create a new configuration file at same path e.g. docker-compose-lamp/config/vhosts/myhost.conf

2. Enter the following virtual host code.

<VirtualHost *:80>
    ServerAdmin webmaster@yourhostname
    DocumentRoot "/var/www/html/your-dir"
    ServerName yourhostname
    <Directory "/var/www/html/your-dir/">
        AllowOverride all
    </Directory>
</VirtualHost>

And save the file.

3. Edit your local machine's host file and add the following entry.
127.0.0.1    yourhostname

Change your ip if it is different.

4. Reload the server by either restarting the docker-compose or reloading the apache server.

I hope this helps.

**Comment by MrOffline77** [comment]
Hi @hungfhq !
thank you for your participation in this project. 
If you want to see this steps in the readme you can create a pull request, and create a tutorial section inside the readme if you want so. 
best regards

**Comment by pablovilla4** [comment]
Hi, I did exactly that from my ubuntu 20.04 and when I use curl from the console it works, but when I use the browser it returns an error 307, which could be ??

in the etc/hosts file in the ubuntu add this:
127.0.0.1 test1.dev

`<VirtualHost *: 80>
    ServerAdmin webmaster@localhost
    DocumentRoot "/var/www/html/test1"
    ServerName test1.dev
<Directory "/var/www/html/test1/">
AllowOverride all
</Directory>
</VirtualHost>`

**Comment by rebroff** [comment]
The new host folder path is docker-compose-lamp/www/betondaily.

```
<VirtualHost *:80> 
    ServerAdmin webmaster@betondaily.local
    ServerName betondaily.local
    DocumentRoot "var/www/html/betondaily"
    <Directory "var/www/html/betondaily"> 
        AllowOverride all
    </Directory> 
</VirtualHost> 
```
/etc/hosts[
![Снимок 29 06 2024 в 20 23](https://github.com/sprintcube/docker-compose-lamp/assets/1961958/b127c86e-322a-4889-a4a0-42d021ff362b)
](url)

I get error 403 Forbidden
