### ISSUE TITLE
how do we change max_upload size? 

### ISSUE THREAD

**Issue by ilovefood2** [sprintcube/docker-compose-lamp#54]
I am trying to upload sql for over 2M but found there is a limit 

![image](https://user-images.githubusercontent.com/4293869/65170977-d722dd00-da17-11e9-9fb2-24252b1e04c3.png)
i also checked php.ini, it has 100M and 20M upload limit
how come phpmyadmin has different upload limit?

**Comment by ilovefood2** [comment]
also, how do we enable ldap support? 
 here is my php.ini and it seems does not work

```
memory_limit = 1280M
post_max_size = 1000M
upload_max_filesize = 200M

extension=php_ldap.dll
ldap.max_links=-1

```

**Comment by narendravaghela** [comment]
Hi @ilovefood2 
The [phpmyadmin](https://hub.docker.com/r/phpmyadmin/phpmyadmin/) is a separate docker image. See https://github.com/sprintcube/docker-compose-lamp/blob/055ee58d51eab5aa6f807eeb0edeebf00a274f03/docker-compose.yml#L34

It is based on Nginx server. So, you can modify the docker-compose.yml file which copies the php.ini to appropriate directory. See the configuration of the webserver.

**Comment by ilovefood2** [comment]
got it, will try that, thx

**Comment by MrOffline77** [comment]
@ilovefood2 does this fixed your problem ?

**Comment by ilovefood2** [comment]
Yes thx

**Comment by BeepingGit** [comment]
How did you configure the docker-compose.yml to copy php.ini. Can you paste the example?
