### ISSUE TITLE
Reset phpmyadmin password

### ISSUE THREAD

**Issue by catarinarpds** [sprintcube/docker-compose-lamp#60]
How can I reset the phpmyadmin password?

**Comment by adrianahdez** [comment]
> How can I reset the phpmyadmin password?
I had to change the password in docker-compose.yml 
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
Then delete the data/mysql folder and then docker-compose down and up again
