### ISSUE TITLE
phpmyadmin - No Privileges

### ISSUE THREAD

**Issue by manish-fn** [sprintcube/docker-compose-lamp#64]
I can't add any database from phpmyadmin.

**Comment by adrianahdez** [comment]
> I can't add any database from phpmyadmin.

Check if you are logged in as root in your phpmyadmin

**Comment by CROSP** [comment]
I have a similar issue.
To solve it just remove these variables from the `docker-compose.yml` file. 
```
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
```
**PMA_USER and PMA_PASSWORD - define username to use for config authentication method**
So, in this case, the config auth method is used and it uses the docker user as defined in config.

**Comment by manish-fn** [comment]
Go it. Thanks
