### ISSUE TITLE
Quick Links URLs

### ISSUE THREAD

**Issue by Michael-A-Sherman** [sprintcube/docker-compose-lamp#66]
Hello,

I ran into an issue with the quick link urls that I think could be fixed quite easily. I was running this on a VM and when I pulled up the IP of the VM on a different machine on my network, the quick links did not work because the quick links use local host.
```
<li><a href="http://localhost/phpinfo.php">phpinfo()</a></li>
<li><a href="http://localhost:8080">phpMyAdmin</a></li>
<li><a href="http://localhost/test_db.php">Test DB Connection</a></li>
```
I feel like this could easily be resolved by changing the links as follows:
``` 
<li><a href="/phpinfo.php">phpinfo()</a></li>
<li><a href="//<?php print $_SERVER{'SERVER_NAME'}; ?>:8080">phpMyAdmin</a></li>
<li><a href="/test_db.php">Test DB Connection</a></li>
```
I would be happy to submit a PR if this is ok.

Thank you

**Comment by MrOffline77** [comment]
Hi @tsh3rman ,
thank your for you participation ! Please feel free to create a pull request for each php version branch.

**Comment by tsh3rman** [comment]
I submitted a pull request on each branch.

**Comment by MrOffline77** [comment]
merged
