### ISSUE TITLE
upgrade to PHP 7.4 and Mysql 8

### ISSUE THREAD

**Issue by avierr** [sprintcube/docker-compose-lamp#70]

**Comment by MrOffline77** [comment]
I'm working on a php74 branch. Mysql8 is no problem. We will create a new WIP php74 branch for this.

**Comment by avierr** [comment]
Thank you

**Comment by MrOffline77** [comment]
php 7.4 has landet take a look at the branches :)

**Comment by avierr** [comment]
Awesome!! Thank you!
