### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by wadimsewo** [sprintcube/docker-compose-lamp#71]
Hi,

I switch the Branch to 7.3.x version of PHP, but still get the 7.1.20 Version.

**Comment by narendravaghela** [comment]
You need to shut down the running containers first via `docker-compose down`. After that step, change the branch and run the following commands.
```
docker-compose build
docker-compose up -d
```

**Comment by MrOffline77** [comment]
does this solved you problem ? @wadimsewo

**Comment by MrOffline77** [comment]
Closed due to now response.
