### ISSUE TITLE
Laravel Installation

### ISSUE THREAD

**Issue by mourareaupro** [sprintcube/docker-compose-lamp#77]
Hello, i'm new on docker, i installed a new laravel application under /var/www 
cd my app
php artisan serve

when i go to 127.0.0.1:8000 i get proxy errror.

do you know why ?

**Comment by MrOffline77** [comment]
Hi,
`php artisan server`gives you a local dev php server. This has nothing to do with the docker compose here. Please take a look at the readme inside our php version branches.

**Comment by mourareaupro** [comment]
thanks a lot :)
