### ISSUE TITLE
webserver docker file fails on Freetype command

### ISSUE THREAD

**Issue by DaveMeade** [sprintcube/docker-compose-lamp#78]
When I run docker-compose up -d, the process eventually fails with the following error:

`configure: error: unrecognized options: --with-freetype-dir, --with-jpeg-dir
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c apt-get -y update &&     apt-get --no-install-recommends install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev &&     rm -rf /var/lib/apt/lists/* &&     docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ &&     docker-php-ext-install -j$(nproc) gd' returned a non-zero code: 1`

This appears to be related to the "# Install Freetype " section of the Dockerfile.  When I comment out that portion of the dockerfile, the container runs.

**Comment by MrOffline77** [comment]
Hi please pull the branch again. I fixed this error yesterday 👌. Please let me now if your build works. Happy coding ❤️

**Comment by DaveMeade** [comment]
Thanks @MrOffline77
