### ISSUE TITLE
PhpMyAdmin no privileges

### ISSUE THREAD

**Issue by mourareaupro** [sprintcube/docker-compose-lamp#80]
![Capture d’écran 2019-12-12 à 23 33 45](https://user-images.githubusercontent.com/25173073/70754651-0c4d7b80-1d38-11ea-9c49-8f832b76e8b9.png)

I have no privileges for the user docker. when i go to http://localhost:8080/ i'm logged directly without the auth step. i created containers with the default env config

**Comment by boelle** [comment]
i have the same issue... how did you fix this?
