### ISSUE TITLE
multiple databases

### ISSUE THREAD

**Issue by salimmejdoub** [sprintcube/docker-compose-lamp#81]
how can i add other databases  with all privileges? 

thanks

**Comment by ChrisMc1870** [comment]
Once your container is up and running, you can connect to the database using MySQL Workbench and log in with the MYSQL root credentials and then add your database. Once that is done, you canadd the docker user permissions to the new database.

**Comment by MrOffline77** [comment]
Hi @salimmejdoub does the answer from @ChrisMc1870 solved you issue ? Please let us know.

**Comment by salimmejdoub** [comment]
hello @MrOffline77 , i just tested it now,
it works thanks for your hel @ChrisMc1870

**Comment by fixnixinc** [comment]
How can I add a database by default like you have added docker db?
