### ISSUE TITLE
undefined function mysqli_connect() 

### ISSUE THREAD

**Issue by sasidhar79** [sprintcube/docker-compose-lamp#9]
Hi

When I try to connect from PHP to the mysql database i get the following error 

" Fatal error: Call to undefined function mysqli_connect() in /var/www/html/dbtest.php"

Thank you 

-sasi

**Comment by sasidhar79** [comment]
Please close this issue i have resolved it

**Comment by narendravaghela** [comment]
Great, what was that by the way?
