### ISSUE TITLE
The container status of web server and mysql is "Restarting (1) xxx seconds ago". And can't working

### ISSUE THREAD

**Issue by MinhHungTrinh** [sprintcube/docker-compose-lamp#91]
I  have a problem. The container status of Web Server and MYSQL is "Restarting (1) xxx seconds ago". And it can't work with:
- MacOS 10.15.2
- Docker version 19.03.5
Please help me.
And work fine with: Ubuntu 18.04 and Docker version 19.03.5

**Comment by MrOffline77** [comment]
Please give us a little bit more information. Especially the docker container logs. 
More infos about docker logs: https://docs.docker.com/engine/reference/commandline/logs/

**Comment by sdenathaniel** [comment]
My mysql container was doing the same thing, checking the logs showed there were files from another project in the data folder. Removing those files allowed the container to come up stable. That said I am still having other connect problems but it isn't cycling anymore.

**Comment by MinhHungTrinh** [comment]
> Please give us a little bit more information. Especially the docker container logs.
> More infos about docker logs: https://docs.docker.com/engine/reference/commandline/logs/
These is my docker logs:

**Comment by MrOffline77** [comment]
mhh usually on my mac this works without a problem. You could try to invoke the docker-compose / Docker daemon with `sudo`.

**Comment by MinhHungTrinh** [comment]
> mhh usually on my mac this works without a problem. You could try to invoke the docker-compose / Docker daemon with `sudo`. Do you have an Administrator Account ?
@MrOffline77 
yes, i removed all containers and images. Then run *sudo docker-compose up -d* again. But it still can not working.

**Comment by paolobattistella** [comment]
I have the same issue.
I have solved removing the following line into Dockerfile about Apache
`rm -rf /var/lib/apt/lists/*`

**Comment by MinhHungTrinh** [comment]
OMG, I solved this problem. Thank for all the support!!!
On my Mac OS ( Catalina 10.15), I disabled System Integrity Protection (SIP) and Gatekeeper.  Then, rebooting my computer. I check  2 containers (webserver and MySql) deleted.  Finally,  I run `docker-compose up -d` again and it work fine.

**Comment by t-franz** [comment]
I have the same problem:
MacOS: 11.7
Docker version 20.10.20, build 9fdeb9c
Docker Desktop: 4.13.0
Docker Compose: 1.29.2

Followed the instructions and it works:
```
git clone https://github.com/sprintcube/docker-compose-lamp.git
cd docker-compose-lamp
cp sample.env .env
docker-compose up -d
```
I can access http://localhost and phpMyAdmin at http://localhost:8080/
Then i stopped and started the containers:
```
docker compose stop
docker compose start
```
**... and mysql stopped working: mysql is cycling and tries to restart.**
The log file for the mysql8-Container:
```
2022-11-01 12:34:48+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
[Multiple Times]
chown: changing ownership of '/var/lib/mysql/mysql.sock': No such file or directory
[Multiple Times]
```

Then i removed the content of the data-folder:
`rm -rf data/*`
And started it again:
`docker compose start`

And it works again!
How can i solve this, without loosing everything inside the data-folder?


I'm sorry: It's my first time with Docker. I used MAMP until now and i wanted to switch to Docker ... :-(
Thank you for your help!
