### ISSUE TITLE
MySQL connecttion failed: The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by jgar2020** [sprintcube/docker-compose-lamp#92]
what is the cause for this error?

Error

MySQL said: Documentation
Cannot connect: invalid settings.
mysqli::real_connect(): Unexpected server response while doing caching_sha2 auth: 109
mysqli::real_connect(): (HY000/2006): MySQL server has gone away
phpMyAdmin tried to connect to the MySQL server, and the server rejected the connection. You should check the host, username and password in your configuration and make sure that they correspond to the information given by the administrator of the MySQL server.

**Comment by MrOffline77** [comment]
mysql8 changed some authentication stuff. When you want to use mysql8 you should also use php74. Mysqli and pdo are should be fully compatible with php >74.

**Comment by MrOffline77** [comment]
Does this solve your issue ?
