### ISSUE TITLE
5.6.x Branch - Mac OSX 10.15.2 Cannot Connect to MySQL

### ISSUE THREAD

**Issue by sdenathaniel** [sprintcube/docker-compose-lamp#95]
When using vanilla (no changes) compose file for 5.6 mysql cannot connect on OSX 10.15.2, not sure why this is, 

I get these same errors on other people's docker compose repos not just this one. Works fine on windows 10 machine (with the exception that on phpmyadmin it says php 7+ even though index.php says 5.6) 

![Screen Shot 2020-01-31 at 4 09 55 PM](https://user-images.githubusercontent.com/4368867/73582914-425bd180-4444-11ea-8d62-55a032e376a4.png)

![Screen Shot 2020-01-31 at 4 17 00 PM](https://user-images.githubusercontent.com/4368867/73583089-2147b080-4445-11ea-85d6-2b04068615e3.png)

![Screen Shot 2020-01-31 at 4 18 47 PM](https://user-images.githubusercontent.com/4368867/73583144-64a21f00-4445-11ea-9d64-a8ee34e3022e.png)

Have tried: 
- disabling xamp
- disabling all other containers 
- direct routing IP to 127.0.0.1
- direct routing IP to containers ip 
- localhost 
- container name 
- service name 

Using php 7+ with mysql 8+ works fine but need stable php 5.6 and mysql 5.7 for project :(

**Comment by sdenathaniel** [comment]
Okay found out this is not a networking error, it was due to the mysql container constantly cycling on and off because because there were other files in the data directory. Cleaned that up but now got a permissions issue, 

![Screen Shot 2020-01-31 at 4 33 07 PM](https://user-images.githubusercontent.com/4368867/73583575-ded3a300-4447-11ea-829c-b09d9608d747.png)

Tried using root + tiger but it seems to be locked at network level. Will try creating a new db and setting a new user to see if that works and it is just root that won't connect.

**Comment by sdenathaniel** [comment]
This is related to  - https://github.com/sprintcube/docker-compose-lamp/issues/29 

I am already using container names not IPs though. So I am fairly certain it is hitting the right place just not actually connecting.

**Comment by MrOffline77** [comment]
@sdenathaniel this looks like you system have some kind of firewall not allowing a connect. Please try to undo #72 locally. This should work for you. Please let me know if this works for you.

**Comment by MrOffline77** [comment]
@sdenathaniel for me both works. ( just created two tests with #72 and without ) 



![Bildschirmfoto 2020-02-05 um 15 12 22](https://user-images.githubusercontent.com/43014876/73849545-69dae180-482a-11ea-8a45-b104ea54d41e.png)
![Bildschirmfoto 2020-02-05 um 15 12 16](https://user-images.githubusercontent.com/43014876/73849551-6e06ff00-482a-11ea-9549-dc5a91655ca8.png)

**Comment by Yop-La** [comment]
I have the same issue  event without #72 !

**Comment by wadimsewo** [comment]
This solution worked for me:

1. **Container console:** docker exec -i 5.7-mysql bash
2. **Create new user for all networks:** CREATE USER 'root'@'%' IDENTIFIED BY 'tiger'; 
3. **Allow all connections:** GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

**Comment by MrOffline77** [comment]
Thanks for sharing your solution @wadimsewo 

If anyone wants to create a pull request to fix this, I would appreciate this! I'm at the moment not able to reproduce the issue.

**Comment by MrOffline77** [comment]
Let me know if this issue is fixed know.

**Comment by ayoubgm** [comment]
The lamp_databse container keep restarting him self and can't open bash, and logs of the container it keeps aborting 
<img width="1594" alt="Screen Shot 2020-10-21 at 11 40 01 PM" src="https://user-images.githubusercontent.com/46103801/96794847-dcaadd80-13f6-11eb-9d83-a9174680be29.png">
