### ISSUE TITLE
ERROR: Service 'webserver' failed to build: Invalid signal: SIGWINCH

### ISSUE THREAD

**Issue by jpzapata99** [sprintcube/docker-compose-lamp#97]
I'm trying to use this proyect but when I put the command: docker-compose up -d
The system gime me:
Step 1/10 : FROM php:7.4.1-apache-buster
 ---> 0c37fe4343a5
Step 2/10 : ARG DEBIAN_FRONTEND=noninteractive
ERROR: Service 'webserver' failed to build: Invalid signal: SIGWINCH
I'm new with Docker so I don't know if may be I'm in a classic error.
I haven't do any change in code.

**Comment by MrOffline77** [comment]
Hi, this sound like a local thing with your mashine. Due to this isn‘t a bug im going to close this issie sorry.
