### ISSUE TITLE
Mailhog [FEATURE]

### ISSUE THREAD

**Issue by dokker** [sprintcube/docker-compose-lamp#99]
Hi,

Would you consider to add Mailhog to the stack? Or any other possibility to catch the emails?

**Comment by MrOffline77** [comment]
Hi @dokker did you consider using mailtrap for example ? They are doing exactly that for free.

**Comment by dokker** [comment]
[Mailhog](https://github.com/mailhog/MailHog) has MIT license so it is for free in practice. It is widespread to just catching mails in dev environments.
Anyway I'll try to use a mailhog container with docker-compose-lamp somehow. 
Thanks @MrOffline77
